import sys
orig = open("ai_evals_comprehensive_study_guide.md", encoding="utf-8").read()
orig_lines = orig.splitlines(keepends=True)
cb = lambda s, e: "".join(orig_lines[s-1:e])
out = open("ai_evals_comprehensive_study_guide.md.new", "w", encoding="utf-8")
w = out.write

w('# ── Title + Intro (lines 1-54) ──────────────────────────────────────────────')
w('<a id="ai-evals-for-engineers-pms--qas-complete-study-guide"></a>\n')
w('# 工程師、PM 與 QA 的 AI 評測完全學習指南\n')
w('\n')
w('*基於 Hamel Husain 與 Shreya Shankar 在 Maven 的課程，結合實踐範例、生產就緒程式碼，以及針對 Phoenix、Langfuse 等平台的詳細指南*\n')
w('\n')
w('**這份指南適合誰？**\n')
w('- **工程師**：正在開發 AI 驅動產品，需要系統性地評估品質\n')
w('- **產品經理（PM）**：負責產品體驗，需要主導錯誤分析\n')
w('- **QA 工程師**：需要為 AI 系統建立自動化評測管線\n')
w('- **任何人**：想學習如何評測 AI 應用程式，而不必修完整門課程\n')
w('\n')
w('**你將學到：**\n')
w('- 如何為任何 AI 應用程式設置可觀測性\n')
w('- 如何系統性地找出問題所在（錯誤分析）\n')
w('- 如何建立自動化評測器（基於程式碼的評測器與 LLM judge）\n')
w('- 如何評測 RAG 系統、多步驟管線與多輪對話\n')
w('- 如何執行生產環境評測：護欄、安全性與即時監控\n')
w('- 如何使用統計修正來補償 judge 的偏差\n')
w('- 如何形成閉環：將評測結果轉化為系統改進\n')
w('- 如何使用你選擇的可觀測性平台完成上述一切（Phoenix、Langfuse、Braintrust、LangSmith，或自建平台）\n')
w('\n')
w('**平台範例：** 本指南以 **Arize Phoenix**（開源、自架）和 **Langfuse**（開源、雲端或自架）為主要範例。方法論是平台中立的——請依你使用的工具自行調整。\n')
w('\n')
w('---\n')
w('\n')
w('<a id="table-of-contents"></a>\n')
w('## 目錄\n')
w('\n')
w('1. [AI 評測是什麼，以及為什麼你需要它們](#chapter-1)\n')
w('2. [設置可觀測性](#chapter-2)\n')
w('3. [錯誤分析：秘密武器](#chapter-3)\n')
w('4. [建立 LLM-as-a-Judge 評測器](#chapter-4)\n')
w('5. [基於程式碼的評測器](#chapter-5)\n')
w('6. [RAG 系統評測](#chapter-6)\n')
w('7. [多步驟管線評測](#chapter-7)\n')
w('8. [多輪對話評測](#chapter-8)\n')
w('9. [生產環境評測：安全性、護欄與監控](#chapter-9)\n')
w('10. [使用 judgy 進行統計修正](#chapter-10)\n')
w('11. [形成閉環：從評測到改進](#chapter-11)\n')
w('12. [人工標注最佳實踐](#chapter-12)\n')
w('13. [成本、延遲與評測擴展](#chapter-13)\n')
w('14. [實踐實施指南](#chapter-14)\n')
w('15. [常見錯誤避免指南](#chapter-15)\n')
w('16. [工具與資源](#chapter-16)\n')
w('\n')
w('**附錄：**\n')
w('- [A：PM 與 QA 詞彙表](#appendix-a)\n')
w('- [B：快速參考](#appendix-b)\n')
w('- [C：生產環境中完整的 judge prompt](#appendix-c)\n')
w('- [D：管線狀態評測器 prompt](#appendix-d)\n')
w('- [E：Judge Prompt 工程技巧](#appendix-e)\n')
w('- [F：平台方法參考（Phoenix 與 Langfuse）](#appendix-f)\n')
w('- [G：30 天學習路徑](#appendix-g)\n')
w('\n')
w('---\n')
w('\n')
w('# ── Chapter 1 (lines 55-141) ──────────────────────────────────────────────')
w('<a name="chapter-1"></a>\n')
w('<a id="chapter-1-what-are-ai-evals-and-why-you-need-them"></a>\n')
w('## Chapter 1：AI 評測是什麼，以及為什麼你需要它們\n')
w('\n')
w('<a id="simple-definition"></a>\n')
w('### 簡單的定義\n')
w('\n')
w('**評測（Evals，全稱 Evaluations）** 是用來系統性地確認 AI 應用程式是否正確運作的測試。可以把它們想像成傳統軟體的單元測試，但針對的是 AI 系統。\n')
w('\n')
w('<a id="why-everyone-needs-evals"></a>\n')
w('### 為什麼每個人都需要評測\n')
w('\n')
w('關於 AI 社群有一場爭論：有些人說「直接感受一下就好」（意思是：自己試用看看，感覺不錯就行了）。但事實是：\n')
w('\n')
w('**每個人都需要評測。** 那些說不需要評測的人，其實是在受益於別人上游做的評測。\n')
w('\n')
w('範例：如果你用 GPT-4 建立了一個程式碼助理，OpenAI 已經在大量程式碼基準測試上測試過 GPT-4。所以你可以「感受一下」。但對於大多數不是基礎模型簡單用途的應用，你需要自己的評測。\n')
w('\n')
w('<a id="the-three-core-truths-about-evals"></a>\n')
w('### 關於評測的三個核心事實\n')
w('\n')
w('1. **你無法改善你沒有量測的事物**\n')
w('   - 「有用性分數」這類通用指標無法捕捉特定問題\n')
w('   - 你需要針對應用程式的特定評測\n')
w('\n')
w('2. **錯誤分析是最重要的步驟**\n')
w('   - 比 LLM judge 更重要\n')
w('   - 比精美的可觀測性工具更重要\n')
w('   - 這才是你真正學到哪裡出了問題的地方\n')
w('\n')
w('3. **PM 與 QA 必須負責錯誤分析，而不只是工程師**\n')
w('   - 工程師知道程式碼是否運作\n')
w('   - PM 知道產品體驗是否良好\n')
w('   - QA 知道如何系統性地找出問題\n')
w('   - 你擁有領域專業知識\n')
w('   - 這是產品工作，而不只是技術工作\n')
w('\n')
w('<a id="the-ai-development-cycle-is-the-scientific-method"></a>\n')
w('### AI 開發週期就是科學方法\n')
w('\n')
w('打造卓越的 AI 產品需要嚴謹的評測流程。在許多方面，AI 開發就是科學方法：\n')
w('\n')
w('1. **觀察** - 追蹤 AI 的行為（第 2 章）\n')
w('2. **假設** - 透過錯誤分析找出問題（第 3 章）\n')
w('3. **實驗** - 建立評測器並測試變更（第 4–9 章）\n')
w('4. **量測** - 計算指標並修正偏差（第 10 章）\n')
w('5. **迭代** - 根據數據改進，而非靠直覺（第 11 章）\n')
w('\n')
w('<a id="what-can-go-wrong-without-evals"></a>\n')
w('### 沒有評測會出什麼問題？\n')
w('\n')
w('你的示範運作得很好。然後上線了：\n')
w('\n')
w('- 使用者遇到你從未想過的邊緣案例\n')
w('- 文字訊息包含錯字和不尋常的格式\n')
w('- 日期的格式與預期不同\n')
w('- AI 嘗試處理應該轉交給真人的請求\n')
w('- 小幅修改 prompt 就會讓原本運作的功能壞掉\n')
w('\n')
w('**來自真實生產資料的範例：**\n')
w('w(cb(109, 115))')
w('\n')
w('同一次互動中出現了三個不同的問題！沒有適當的日誌記錄和評測，你永遠不會發現這些模式。\n')
w('\n')
w('<a id="for-pms-why-this-is-your-job"></a>\n')
w('### 給 PM：為什麼這是你的工作\n')
w('\n')
w('**錯誤的做法：**「這是技術性的 AI 事務，讓工程師去解決就好」\n')
w('\n')
w('**正確的做法：** PM 應該主導錯誤分析，因為：\n')
w('1. 你了解使用者需求\n')
w('2. 你擁有產品品味\n')
w('3. 你擁有領域專業知識\n')
w('4. 這是披著技術外衣的產品工作\n')
w('\n')
w('**打造出最佳 AI 產品的團隊，擁有親自審閱過數百甚至數千條追蹤記錄的 PM。**\n')
w('\n')
w('<a id="for-qas-your-new-superpower"></a>\n')
w('### 給 QA：你的新超能力\n')
w('\n')
w('傳統 QA 涉及有預期輸出的測試案例。AI QA 則不同：\n')
w('1. 輸出是不確定的（相同輸入可能產生不同輸出）\n')
w('2. 「正確」往往是主觀的\n')
w('3. 邊緣案例幾乎是無限的\n')
w('4. 你需要可擴展的自動化評測器\n')
w('\n')
w('但核心的 QA 思維——系統性測試、邊緣案例思維、回歸預防——正是 AI 評測所需要的。學會評測的 QA 工程師將變得極具價值。\n')
w('\n')
w('---\n')
w('\n')
# ── Chapter 2 (lines 143-425) ──────────────────────────────────────────────
w('<a name="chapter-2"></a>\n')
w('<a id="chapter-2-setting-up-observability"></a>\n')
## Chapter 2：設置可觀測性

w('\n')
w('<a id="what-is-a-trace"></a>\n')
### 什麼是追蹤記錄（Trace）？

w('\n')
w('**追蹤記錄（trace）** 是 AI 在回應使用者時所做一切的完整記錄。就像詳細的日誌，顯示：\n')
w('\n')
w('1. **系統 prompt**（給 AI 的指示）\n')
w('2. **使用者訊息**（使用者的提問）\n')
w('3. **工具呼叫**（AI 嘗試使用的函式）\n')
w('4. **工具回應**（那些函式回傳的結果）\n')
w('5. **助理回應**（AI 的回覆）\n')
w('6. **所有上下文**（LLM 在做決策時看到的一切）\n')
w('\n')
w('<a id="example-of-a-complete-trace"></a>\n')
### 完整追蹤記錄的範例

w('\n')
w(cb(159, 180))
w('\n')
w('<a id="what-information-to-capture"></a>\n')
### 要記錄哪些資訊

w('\n')
w('**最低需求：**\n')
w('- 輸入（使用者訊息）\n')
w('- 輸出（AI 回應）\n')
w('- 時間戳記\n')
w('- 互動的唯一識別碼\n')
w('\n')
w('**建議包含：**\n')
w('- 使用的系統 prompt\n')
w('- 工具呼叫及其結果\n')
w('- 模型參數（temperature、max_tokens 等）\n')
w('- Token 數量\n')
w('- 延遲（回應時間）\n')
w('- 每次請求的成本\n')
w('\n')
w('**最佳實踐：**\n')
w('- 使用者上下文（對話歷史）\n')
w('- 發生的錯誤訊息（如有）\n')
w('- 使用的模型版本\n')
w('- 當時啟用的功能開關\n')
w('\n')
w('<a id="choosing-an-observability-platform"></a>\n')
### 選擇可觀測性平台

w('\n')
w('| 工具 | 類型 | 最適合 | 費用 |\n')
w('|------|------|----------|------|\n')
w('| **Arize Phoenix** | 開源、自架 | 功能完整，單一 Docker 容器 | 免費 |\n')
w('| **Langfuse** | 開源、雲端或自架 | 精緻 UI，強大社群 | 免費方案 + 付費 |\n')
w('| **Braintrust** | 雲端 | 出色 UI，團隊協作 | 付費 |\n')
w('| **LangSmith** | 雲端 | LangChain 使用者 | 付費 |\n')
w('| **自行建立** | 自訂 | 學習、自訂需求 | 免費 |\n')
w('\n')
w('所有這些平台都支援相同的核心概念：追蹤記錄（traces）、跨度（spans）、資料集、評測和實驗。本指南的方法論適用於任何一個。\n')
w('\n')
w('<a id="setting-up-phoenix-open-source-self-hosted"></a>\n')
### 設置 Phoenix（開源、自架）

w('\n')
w('Phoenix 是一個基於 OpenTelemetry 構建的開源 AI 可觀測性平台。它提供追蹤記錄、評測、資料集、實驗和 prompt 管理——完全免費。\n')
w('\n')
w('<a id="install-and-start"></a>\n')
#### 安裝與啟動

w('\n')
w(cb(222, 226))
w('\n')
w('<a id="instrument-your-application"></a>\n')
#### 為你的應用程式添加儀器

w('\n')
w(cb(230, 241))
w('\n')
w('<a id="your-openai-calls-are-now-traced"></a>\n')
#### 你的 OpenAI 呼叫現在已被追蹤

w('\n')
w(cb(245, 259))
w('\n')
w('<a id="add-custom-spans"></a>\n')
#### 新增自訂跨度

w('\n')
w(cb(263, 275))
w('\n')
w('<a id="setting-up-langfuse-open-source-cloud-or-self-hosted"></a>\n')
### 設置 Langfuse（開源、雲端或自架）

w('\n')
w('Langfuse 提供追蹤記錄、評測、資料集、實驗和 prompt 管理。它提供託管雲端和自架選項。\n')
w('\n')
w('<a id="install-and-configure"></a>\n')
#### 安裝與設定

w('\n')
w(cb(283, 292))
w('\n')
w('<a id="instrument-your-application-drop-in-replacement"></a>\n')
#### 為你的應用程式添加儀器（直接替換）

w('\n')
w(cb(296, 311))
w('\n')
w('<a id="add-custom-spans-with-decorators"></a>\n')
#### 使用裝飾器新增自訂跨度

w('\n')
w(cb(315, 329))
w('\n')
w('<a id="creating-and-managing-prompts"></a>\n')
### 建立與管理 Prompt

w('\n')
w('兩個平台都支援有版本控制的 prompt 管理：\n')
w('\n')
w('<a id="phoenix"></a>\n')
#### Phoenix

w('\n')
w(cb(337, 351))
w('\n')
w('<a id="langfuse"></a>\n')
#### Langfuse

w('\n')
w(cb(355, 373))
w('\n')
w('<a id="uploading-test-datasets"></a>\n')
### 上傳測試資料集

w('\n')
w('<a id="phoenix-1"></a>\n')
#### Phoenix

w('\n')
w(cb(379, 398))
w('\n')
w('<a id="langfuse-1"></a>\n')
#### Langfuse

w('\n')
w(cb(402, 416))
w('\n')
w('<a id="key-principle"></a>\n')
### 關鍵原則

w('\n')
w('**沒有追蹤記錄，就無法進行評測。** 這是你的基礎。在做任何其他事情之前，先設置好這個。\n')
w('\n')
w('**給 PM/QA：** 你不需要編寫儀器化程式碼。請工程師設置追蹤記錄，然後使用 Web UI 以視覺化方式查看追蹤記錄。Phoenix（`localhost:6006`）和 Langfuse（`cloud.langfuse.com` 或你的自架 URL）都提供 UI，讓你無需編寫任何程式碼即可瀏覽、搜尋和標注追蹤記錄。\n')
w('\n')
w('---\n')
w('\n')
# ── Chapter 3 (lines 426-753) ──────────────────────────────────────────────
w('<a name="chapter-3"></a>\n')
w('<a id="chapter-3-error-analysis-the-secret-sauce"></a>\n')
## Chapter 3：錯誤分析：秘密武器

w('\n')
w('<a id="what-is-error-analysis"></a>\n')
### 什麼是錯誤分析？

w('\n')
w('錯誤分析是一個**系統性流程**，包含：\n')
w('1. 審閱追蹤記錄（AI 互動的日誌）\n')
w('2. 記錄你發現的問題\n')
w('3. 對這些問題進行分類\n')
w('4. 統計每種問題類型的發生頻率\n')
w('\n')
w('**這是**建立可靠 AI 產品**最重要的技能**。\n')
w('\n')
w('大多數團隊直接跳到建立精美的儀表板或 LLM judge。這是本末倒置的。你需要先理解哪裡出了問題，然後才能量測它。\n')
w('\n')
w('<a id="why-pms-and-qas-must-do-this-not-just-engineers"></a>\n')
### 為什麼 PM 與 QA 必須參與（而不只是工程師）

w('\n')
w('**錯誤的做法：**\n')
w('「這是技術性的 AI 事務，讓工程師去解決就好」\n')
w('\n')
w('**正確的做法：**\n')
w('PM 與 QA 應該主導錯誤分析，因為：\n')
w('\n')
w('1. **你了解使用者需求** - 工程師不知道「連結浴室」vs「獨立浴室」對使用者是否重要\n')
w('2. **你有產品品味** - 你知道好的體驗是什麼樣子\n')
w('3. **你有領域專業知識** - 你理解商業需求\n')
w('4. **這是產品工作** - 披著技術外衣，但本質上是關於產品品質的\n')
w('\n')
w('**實際影響：**\n')
w('打造出最佳 AI 產品的團隊，擁有親自審閱過數百甚至數千條追蹤記錄的 PM。\n')
w('\n')
w('<a id="step-1-generate-diverse-test-queries"></a>\n')
### 步驟 1：生成多樣化的測試查詢

w('\n')
w('在審閱追蹤記錄之前，你需要多樣化的測試輸入。一個強大的技術是**維度抽樣**。\n')
w('\n')
w('<a id="define-key-dimensions"></a>\n')
#### 定義關鍵維度

w('\n')
w('找出對你的產品重要的 3-4 個維度：\n')
w('\n')
w(cb(465, 482))
w('\n')
w('<a id="generate-random-combinations"></a>\n')
#### 生成隨機組合

w('\n')
w(cb(486, 500))
w('\n')
w('<a id="convert-tuples-to-natural-language-queries-using-an-llm"></a>\n')
#### 使用 LLM 將元組轉換為自然語言查詢

w('\n')
w('你可以使用任何 LLM 將維度元組轉換為真實查詢。以下是一個平台中立的方法，以及一個 Phoenix 特定的批次方法：\n')
w('\n')
w('**使用任何 LLM（平台中立）：**\n')
w('\n')
w(cb(508, 530))
w('\n')
w('**使用 Phoenix（批次生成）：**\n')
w('\n')
w(cb(534, 548))
w('\n')
w('**轉換範例：**\n')
w('\n')
w('| 維度元組 | 生成的查詢 |\n')
w('|---|---|\n')
w('| vegan、Italian、dinner、beginner | 「嘿，我是新手，也是素食者。你能推薦一個簡單的義大利晚餐嗎？」 |\n')
w('| gluten-free、any、dessert、intermediate | 「我在找一個有點挑戰性的無麩質甜點」 |\n')
w('| keto、American、breakfast、advanced | 「給我一個複雜的生酮早餐食譜，美式風格」 |\n')
w('\n')
w('**給 PM/QA：** 這種維度方法確保你測試完整的使用者需求空間。沒有它，你只會測試顯而易見的案例，而錯過使用者組合意外需求的邊緣案例。\n')
w('\n')
w('<a id="step-2-review-100-traces-and-take-notes-open-coding"></a>\n')
### 步驟 2：審閱 100 條追蹤記錄並做筆記（開放編碼）

w('\n')
w('**流程（每條追蹤記錄 30 秒）：**\n')
w('\n')
w('1. 打開你的追蹤記錄查看器（Phoenix UI、Langfuse 儀表板或任何工具）\n')
w('2. 查看第一條追蹤記錄\n')
w('3. 瀏覽它：\n')
w('   - 閱讀使用者訊息\n')
w('   - 確認 AI 是否呼叫了正確的工具\n')
w('   - 查看工具回傳了什麼\n')
w('   - 閱讀助理的回應\n')
w('   - 記錄你發現的任何問題\n')
w('\n')
w('**來自真實錯誤分析會話的筆記範例：**\n')
w('\n')
w(cb(575, 591))
w('\n')
w('**錯誤分析規則：**\n')
w('\n')
w('1. **不要試圖抓住所有問題** - 只記錄最重要的事情\n')
w('2. **不要對每條追蹤記錄爭論** - 快速思考，記下來，繼續前進\n')
w('3. **跳過系統 prompt** - 如果它通常是相同的，你不需要每次都讀\n')
w('4. **進入心流狀態** - 這應該感覺快速，而不是繁瑣\n')
w('\n')
w('**時間承諾：**\n')
w('- 第一條追蹤記錄：45 秒\n')
w('- 10 條後：每條 25 秒\n')
w('- 50 條後：每條 20 秒\n')
w('- **100 條追蹤記錄的總時間：約 45 分鐘**\n')
w('\n')
w('<a id="step-3-categorize-errors-using-axial-coding"></a>\n')
### 步驟 3：使用軸向編碼對錯誤進行分類

w('\n')
w('現在你有 40-50 條分散在各追蹤記錄中的筆記。是時候整理它們了。\n')
w('\n')
w('這個過程稱為**「軸向編碼」**（一種源自社會學的研究方法）。你正在將相似的錯誤分組為類別。\n')
w('\n')
w('<a id="using-an-llm-to-help-discover-categories"></a>\n')
#### 使用 LLM 幫助發現類別

w('\n')
w('匯出你的筆記，然後使用此 prompt：\n')
w('\n')
w(cb(616, 636))
w('\n')
w('**來自真實食譜機器人評測的結果範例：**\n')
w('\n')
w(cb(640, 643))
w('\n')
w('<a id="refine-categories-to-be-specific-and-actionable"></a>\n')
#### 細化類別以使其具體且可操作

w('\n')
w('**問題：** 通用的 LLM 建議太模糊！\n')
w('\n')
w('「時間問題」——這是什麼意思？\n')
w('「品質問題」——太籠統！\n')
w('\n')
w('**更好的類別（具體且可操作）：**\n')
w('\n')
w('1. **飲食限制被忽略** - 機器人建議違反飲食限制的食材\n')
w('2. **格式錯誤** - 在 SMS 中使用 Markdown、結構錯誤\n')
w('3. **複雜度不匹配** - 食譜對於聲明的技能等級太難/太簡單\n')
w('4. **餐食類型不匹配** - 詢問早餐時卻建議晚餐\n')
w('5. **食材遺漏** - 沒有包含使用者要求的特定食材\n')
w('6. **技能等級不一致** - 對初學者使用高級技巧\n')
w('\n')
w('**你的類別需要足夠具體，以便其他人能夠用它們來標注錯誤。**\n')
w('\n')
w('<a id="step-4-label-your-errors-with-llm-assistance"></a>\n')
### 步驟 4：使用 LLM 協助標注錯誤

w('\n')
w('此步驟適用於任何 LLM。如果你的平台支援，請使用批次處理：\n')
w('\n')
w(cb(667, 682))
w('\n')
w('<a id="step-5-count-and-prioritize"></a>\n')
### 步驟 5：計數並排定優先順序

w('\n')
w('**統計每個類別出現的次數：**\n')
w('\n')
w(cb(688, 690))
w('\n')
w('**來自真實評測的結果範例：**\n')
w('\n')
w('| 類別 | 次數 | 百分比 |\n')
w('|----------|-------|------------|\n')
w('| 複雜度不匹配 | 2 | 22% |\n')
w('| 餐食類型不匹配 | 2 | 22% |\n')
w('| 食材遺漏 | 2 | 22% |\n')
w('| 飲食限制被忽略 | 1 | 11% |\n')
w('| 格式錯誤 | 1 | 11% |\n')
w('| 技能等級不一致 | 1 | 11% |\n')
w('\n')
w('<a id="why-this-changes-everything"></a>\n')
### 為什麼這改變了一切

w('\n')
w('**錯誤分析之前：**\n')
w('- 你一籌莫展\n')
w('- 不知道先修什麼\n')
w('- 無法排定優先順序\n')
w('\n')
w('**錯誤分析之後：**\n')
w('- 基於頻率的清晰優先順序\n')
w('- 了解嚴重性（頻率 vs. 影響）\n')
w('- 用於與利害關係人討論的證據\n')
w('- 要建立哪些評測器的具體清單\n')
w('\n')
w('**優先順序討論範例：**\n')
w('\n')
w(cb(718, 726))
w('\n')
w('<a id="the-theoretical-saturation-concept"></a>\n')
### 「理論飽和」概念

w('\n')
w('**何時停止審閱追蹤記錄？**\n')
w('\n')
w('在定性研究中，有一個稱為「理論飽和」的概念——當你停止發現新類型的錯誤時。\n')
w('\n')
w('- 審閱前 50 條追蹤記錄：你發現 10 種不同的錯誤類型\n')
w('- 審閱接下來 25 條：你發現 2 種新錯誤類型\n')
w('- 審閱接下來 25 條：你發現 0 種新錯誤類型\n')
w('- **在這裡停止！** 你已達到飽和\n')
w('\n')
w('如果你在 100 條之後沒有發現新模式，你不需要審閱 1000 條追蹤記錄。\n')
w('\n')
w('<a id="for-pmsqas-your-error-analysis-checklist"></a>\n')
### 給 PM/QA：你的錯誤分析清單

w('\n')
w('1. 請工程師設置追蹤記錄（Phoenix、Langfuse 或任何工具）\n')
w('2. 打開追蹤記錄查看器 UI\n')
w('3. 瀏覽 100 條追蹤記錄，快速記錄問題\n')
w('4. 使用 LLM 將你的筆記分類為 4-6 種失敗模式\n')
w('5. 統計每種失敗模式的出現次數\n')
w('6. 同時考慮頻率和嚴重性，建立優先順序清單\n')
w('7. 向你的團隊提交有數據支持的建議\n')
w('8. 每月重複，使用新的追蹤記錄以發現新的失敗模式\n')
w('\n')
w('---\n')
w('\n')
# ── Chapter 4 (lines 754-1208) ──────────────────────────────────────────────
w('<a name="chapter-4"></a>\n')
w('<a id="chapter-4-building-llm-as-a-judge-evaluators"></a>\n')
## Chapter 4：建立 LLM-as-a-Judge 評測器

w('\n')
w('<a id="what-is-llm-as-a-judge"></a>\n')
### 什麼是 LLM-as-a-Judge？

w('\n')
w('**LLM judge** 是一個評估其他 AI 輸出的 AI。它讀取追蹤記錄並給分。\n')
w('\n')
w('**為什麼使用它？**\n')
w('- 自動化大規模評測\n')
w('- 提供一致的判斷\n')
w('- 比人工審閱快得多\n')
w('\n')
w('**挑戰：**\n')
w('大多數人建立的 judge 是錯的。它們會幻覺、遺漏問題，或造成虛假的信心。\n')
w('\n')
w('<a id="when-to-use-llm-as-a-judge"></a>\n')
### 何時使用 LLM-as-a-Judge

w('\n')
w('**適合用 LLM judge：**\n')
w('- 主觀品質評估\n')
w('- 政策合規性檢查\n')
w('- 上下文理解\n')
w('- 飲食遵循\n')
w('- 語調適切性\n')
w('- 多步驟推理檢查\n')
w('\n')
w('**不適合用 LLM judge：**\n')
w('- 格式驗證（用程式碼）\n')
w('- 必填欄位檢查（用程式碼）\n')
w('- 簡單模式匹配（用程式碼）\n')
w('- 完全字串匹配（用程式碼）\n')
w('\n')
w('**經驗法則：** 如果你能用 if/else 陳述式表達，就用程式碼。如果需要判斷，就用 LLM。\n')
w('\n')
w('<a id="the-complete-llm-judge-workflow"></a>\n')
### 完整的 LLM Judge 工作流程

w('\n')
w('建立可靠的 LLM judge 需要嚴格的 7 步驟工作流程：\n')
w('\n')
w('<a id="overview-the-pipeline"></a>\n')
#### 概覽：流程

w('\n')
w(cb(793, 801))
w('\n')
w('<a id="step-1-generate-traces"></a>\n')
### 步驟 1：生成追蹤記錄

w('\n')
w('在多樣化的測試查詢上執行你的 AI 系統，以建立追蹤記錄。使用你的平台的自動儀器化（見 Chapter 2）來自動捕獲一切。\n')
w('\n')
w('<a id="step-2-label-ground-truth-data"></a>\n')
### 步驟 2：標注基準真值資料

w('\n')
w('將 150-200 條追蹤記錄標注為 PASS 或 FAIL。你可以手動（最準確）或使用強大的 LLM 來完成：\n')
w('\n')
w(cb(811, 830))
w('\n')
w('<a id="step-3-split-data-train--dev--test"></a>\n')
### 步驟 3：分割資料（Train / Dev / Test）

w('\n')
w('這一步很關鍵，經常被跳過！你需要三個獨立的集合：\n')
w('\n')
w('- **Train（約 15%）：** 用於為你的 judge prompt 選取少樣本（few-shot）範例\n')
w('- **Dev（約 40%）：** 用於迭代和改進你的 judge prompt\n')
w('- **Test（約 45%）：** 僅使用一次，用於最終的無偏評估\n')
w('\n')
w(cb(840, 856))
w('\n')
w('<a id="step-4-develop-your-judge-prompt"></a>\n')
### 步驟 4：開發你的 Judge Prompt

w('\n')
w('一個好的 judge prompt 包含四個部分：\n')
w('\n')
w('<a id="part-1-task-definition"></a>\n')
#### Part 1：任務定義

w('\n')
w(cb(866, 879))
w('\n')
w('<a id="part-2-criterion-definition"></a>\n')
#### Part 2：標準定義

w('\n')
w(cb(883, 891))
w('\n')
w('<a id="part-3-few-shot-examples"></a>\n')
#### Part 3：少樣本範例

w('\n')
w(cb(896, 915))
w('\n')
w('<a id="part-4-output-format"></a>\n')
#### Part 4：輸出格式

w('\n')
w(cb(919, 928))
w('\n')
w('<a id="why-binary-scores-work-best"></a>\n')
### 為什麼二元分數效果最好

w('\n')
w('**有些人想要 1-5 等級或百分比。不要這樣做。**\n')
w('\n')
w('**使用二元（PASS/FAIL）：**\n')
w('- 只需要驗證兩件事\n')
w('- 決策邊界清晰\n')
w('- 更容易除錯\n')
w('- 更易向利害關係人解釋\n')
w('\n')
w('**使用 1-5 等級：**\n')
w('- 需要驗證每個分數是否一致\n')
w('- 2 和 3 之間的差別是什麼？\n')
w('- 5 倍的驗證工作量\n')
w('- 商業決策本就是二元的\n')
w('\n')
w('**記住：** 你要麼修復某個問題，要麼不修復。要麼壞掉，要麼沒有。\n')
w('\n')
w('<a id="step-5-validate-on-dev-set"></a>\n')
### 步驟 5：在 Dev 集合上驗證

w('\n')
w('在 Dev 集合上執行你的 judge 並與基準真值比較。以下是各平台的作法：\n')
w('\n')
w('<a id="evaluator-functions-platform-agnostic"></a>\n')
#### 評測器函式（平台無關）

w('\n')
w(cb(954, 978))
w('\n')
w('<a id="running-the-experiment"></a>\n')
#### 執行實驗

w('\n')
w(cb(984, 1013))
w('\n')
w('<a id="the-metrics-that-actually-matter"></a>\n')
### 真正重要的指標

w('\n')
w('**大多數人只看「一致性（agreement）」：**\n')
w('\n')
w(cb(1019, 1022))
w('\n')
w('**為什麼這具有誤導性：**\n')
w('\n')
w('如果失敗只發生 10% 的時間，一個總是說「pass」的 judge 因為完全無用而得到 90% 的準確率！\n')
w('\n')
w('**你真正需要的兩個指標：**\n')
w('\n')
w('<a id="1-tpr-true-positive-rate---recall"></a>\n')
#### 1. TPR（真正例率）- 召回率

w('\n')
w('**「當實際上是 PASS 時，judge 多常正確地說 PASS？」**\n')
w('\n')
w(cb(1034, 1036))
w('\n')
w('<a id="2-tnr-true-negative-rate---specificity"></a>\n')
#### 2. TNR（真負例率）- 特異性

w('\n')
w('**「當實際上是 FAIL 時，judge 多常正確地說 FAIL？」**\n')
w('\n')
w(cb(1042, 1044))
w('\n')
w('<a id="real-results-why-iteration-matters"></a>\n')
### 真實結果：為什麼迭代很重要

w('\n')
w('**謹慎的 prompt 迭代後（生產品質的 judge）：**\n')
w('\n')
w(cb(1050, 1058))
w('\n')
w('<a id="prompt-iteration-tips"></a>\n')
### Prompt 迭代技巧

w('\n')
w(cb(1062, 1067))
w('\n')
w('**關鍵洞察：**\n')
w('\n')
w('1. **從 Train 集合中選取 FP/FN 作為少樣本範例** - 使用你的 judge 在 Dev 集合中搞錯的例子\n')
w('2. **要具體說明什麼是 FAIL** - 給出每個限制的精確違反範例\n')
w('3. **以 FAIL 案例開頭你的少樣本範例** - LLM 更注意最近的例子\n')
w('4. **每個飲食限制使用不同的 judge** - 更好地控制 TPR/TNR\n')
w('5. **使用 temperature=0** - 確保一致性\n')
w('6. **為什麼要使用強大的 LLM（GPT-4o、Claude 等）** - 品質 > 成本用於評測\n')
w('7. **然後在 Test 集合上測試一次以獲得最終的無偏指標**\n')
w('\n')
w('<a id="step-6-final-evaluation-on-test-set"></a>\n')
### 步驟 6：在 Test 集合上進行最終評估

w('\n')
w('一旦你的 judge 在 Dev 上表現良好，在 Test 集合上執行一次：\n')
w('\n')
w(cb(1106, 1118))
w('\n')
w('<a id="step-7-run-on-all-traces-at-scale"></a>\n')
### 步驟 7：大規模執行所有追蹤記錄

w('\n')
w('一旦驗證完成，在所有生產追蹤記錄上執行你的 judge：\n')
w('\n')
w(cb(1126, 1167))
w('\n')
w('**結果範例：** 在 1000 條追蹤記錄上的原始通過率 = 84.4%\n')
w('\n')
w('但這個原始比率沒有考慮 judge 的錯誤。Chapter 10 介紹如何使用  函式庫來修正這個問題。\n')
w('\n')
w('<a id="llm-as-judge-across-different-domains"></a>\n')
### LLM-as-Judge 跨不同領域

w('\n')
w('食譜機器人只是一個例子。以下是相同方法論如何應用於其他領域：\n')
w('\n')
w(cb(1178, 1203))
w('\n')
w('結構始終相同：定義標準、撰寫 PASS/FAIL 定義、添加少樣本範例、用 TPR/TNR 驗證。\n')
w('\n')
w('---\n')
w('\n')
# ── Chapter 5 (lines 1209-1386) ──────────────────────────────────────────────
w('<a name="chapter-5"></a>\n')
w('<a id="chapter-5-code-based-evaluators"></a>\n')
## Chapter 5：程式碼型評測器

w('\n')
w('<a id="what-are-code-based-evals"></a>\n')
### 什麼是程式碼型 Eval？

w('\n')
w('程式碼型 eval 是你用**程式語言**（如 Python）撰寫的**檢查**，用於驗證 AI 輸出的特定客觀屬性。\n')
w('\n')
w('<a id="when-to-use-code-based-evals"></a>\n')
### 何時使用程式碼型 Eval

w('\n')
w('**當你不需要呼叫 LLM 就能測試某件事時，使用程式碼：**\n')
w('\n')
w('1. **格式驗證** - Markdown 是否出現在文字訊息中？\n')
w('2. **必填欄位檢查** - AI 是否包含所有必要資訊？\n')
w('3. **工具呼叫驗證** - AI 是否呼叫了正確的工具？\n')
w('4. **回應長度限制** - 回應是否在 500 字元以下？\n')
w('5. **禁止內容模式** - 是否有 PII（電子郵件、電話號碼）？\n')
w('\n')
w('<a id="example-1-check-for-markdown-in-text-messages"></a>\n')
### 範例 1：檢查文字訊息中是否有 Markdown

w('\n')
w(cb(1228, 1254))
w('\n')
w('<a id="example-2-validate-tool-calls"></a>\n')
### 範例 2：驗證工具呼叫

w('\n')
w(cb(1258, 1287))
w('\n')
w('<a id="example-3-validate-required-information-in-tour-confirmations"></a>\n')
### 範例 3：驗證行程確認中的必要資訊

w('\n')
w(cb(1292, 1323))
w('\n')
w('<a id="benefits-of-code-based-evals"></a>\n')
### 程式碼型 Eval 的優點

w('\n')
w('1. **快速** - 無需 API 呼叫，立即得到結果\n')
w('2. **便宜** - 不消耗 token\n')
w('3. **確定性** - 相同輸入始終產生相同輸出\n')
w('4. **易於除錯** - 堆疊追蹤、中斷點都能正常運作\n')
w('5. **無幻覺** - 程式碼完全按照你的指示執行\n')
w('\n')
w('<a id="combining-code-based-and-llm-based-evals"></a>\n')
### 結合程式碼型與 LLM 型 Eval

w('\n')
w('完整的 eval 套件通常包含：\n')
w('- **2-3 個程式碼型 eval** 用於客觀檢查\n')
w('- **1-2 個 LLM 型 eval** 用於主觀判斷\n')
w('\n')
w(cb(1339, 1348))
w('\n')
w('<a id="testing-your-code-based-evals"></a>\n')
### 測試你的程式碼型 Eval

w('\n')
w('**始終用已知的好案例和壞案例測試你的 eval：**\n')
w('\n')
w(cb(1354, 1383))
w('\n')
w('---\n')
w('\n')
# ── Chapter 6 (lines 1387-1589) ──────────────────────────────────────────────
w('<a name="chapter-6"></a>\n')
w('<a id="chapter-6-rag-system-evaluation"></a>\n')
## Chapter 6：RAG 系統評測

w('\n')
w('<a id="what-is-rag"></a>\n')
### 什麼是 RAG？

w('\n')
w('**RAG（檢索增強生成）** 意味著你的 AI：\n')
w('1. **檢索**資料庫中的相關資訊\n')
w('2. **使用該資訊**來生成回應\n')
w('\n')
w('<a id="why-rag-needs-special-evaluation"></a>\n')
### 為什麼 RAG 需要特殊評測

w('\n')
w('RAG 有**兩種失敗模式：**\n')
w('\n')
w('1. **檢索失敗** - 找不到正確資訊\n')
w('2. **生成失敗** - 使用資訊的方式錯誤\n')
w('\n')
w('你需要**分開評測兩者**，才能知道問題出在哪裡。\n')
w('\n')
w('<a id="building-a-bm25-retrieval-engine"></a>\n')
### 建立 BM25 檢索引擎

w('\n')
w('在為特定領域（如食譜）建立關鍵字檢索時，關鍵洞察是：**你的分詞器（tokenizer）很重要**。\n')
w('\n')
w('<a id="custom-tokenizer-for-domain-specific-content"></a>\n')
#### 針對特定領域內容的自訂分詞器

w('\n')
w(cb(1411, 1429))
w('\n')
w('**為什麼這很重要：** 標準分詞器會去除數字。但在食譜中，「375」（溫度）、「9x13」（烤盤尺寸）和「1/2」（量測單位）是關鍵的搜尋詞。\n')
w('\n')
w('<a id="generating-synthetic-queries-for-rag-testing"></a>\n')
### 為 RAG 測試生成合成查詢

w('\n')
w('與其手動撰寫測試查詢，不如使用 LLM 生成依賴文件中特定事實的查詢：\n')
w('\n')
w(cb(1437, 1449))
w('\n')
w('這會生成如下查詢：\n')
w('- 「薑餅城堡餅乾應該烤什麼溫度？」（顯著事實：「350 degrees F for 8-10 minutes」）\n')
w('- 「麵包麵團應該發酵多久？」（顯著事實：「rise for 1 hour until doubled」）\n')
w('\n')
w('（顯著事實）就是你的基準真值——你知道哪個食譜有答案。\n')
w('\n')
w('<a id="evaluating-retrieval-quality"></a>\n')
### 評測檢索品質

w('\n')
w('<a id="recallk"></a>\n')
#### Recall@K

w('\n')
w('「正確食譜是否出現在前 K 個結果中？」\n')
w('\n')
w(cb(1463, 1480))
w('\n')
w('<a id="mean-reciprocal-rank-mrr"></a>\n')
#### 平均倒數排名（MRR）

w('\n')
w('「如果找到了，它的排名有多高？」\n')
w('\n')
w(cb(1486, 1497))
w('\n')
w('<a id="running-retrieval-experiments"></a>\n')
### 執行檢索實驗

w('\n')
w(cb(1503, 1539))
w('\n')
w('<a id="diagnosing-rag-failures"></a>\n')
### 診斷 RAG 失敗

w('\n')
w('當 RAG 測試失敗時，診斷**失敗點**：\n')
w('\n')
w(cb(1545, 1568))
w('\n')
w('<a id="improving-rag-performance"></a>\n')
### 改善 RAG 效能

w('\n')
w('**當檢索失敗時：**\n')
w('1. 嘗試不同的分塊策略\n')
w('2. 添加 metadata 篩選\n')
w('3. 使用混合搜尋（關鍵字 + 語義）\n')
w('4. 實現查詢擴展\n')
w('5. 嘗試重排序模型\n')
w('6. 使用特定領域分詞器（如上面的數字保留版本）\n')
w('\n')
w('**當生成失敗時：**\n')
w('1. 改進系統 prompt\n')
w('2. 添加少樣本範例\n')
w('3. 使用思維鏈（chain-of-thought）提示\n')
w('4. 添加明確的依據指示\n')
w('5. 實現引用要求\n')
w('\n')
w('---\n')
w('\n')
# ── Chapter 7 (lines 1589-1840) ──────────────────────────────────────────────
w('<a name="chapter-7"></a>\n')
w('<a id="chapter-7-multi-step-pipeline-evaluation"></a>\n')
## Chapter 7：多步驟流程評測

w('\n')
w('<a id="what-is-a-multi-step-pipeline"></a>\n')
### 什麼是多步驟流程？

w('\n')
w('**多步驟流程**是指你的 AI 將任務分解為幾個階段，每個階段執行特定工作。\n')
w('\n')
w('<a id="the-7-state-recipe-bot-pipeline"></a>\n')
### 7 狀態食譜機器人流程

w('\n')
w('以下是食譜助理的完整 7 狀態流程範例：\n')
w('\n')
w(cb(1600, 1619))
w('\n')
w('<a id="why-state-level-evaluation-matters"></a>\n')
### 為什麼狀態層級評測很重要

w('\n')
w('**問題：** 如果你的流程失敗，失敗在哪裡？\n')
w('\n')
w('沒有狀態層級 eval，你只知道：\n')
w('- 「系統產生了一個不好的回應」\n')
w('\n')
w('有了狀態層級 eval，你就知道：\n')
w('- 「GenRecipeArgs 狀態丟失了燕麥篩選條件」\n')
w('- 「這導致 GetRecipes 返回了錯誤的食譜」\n')
w('- 「從而產生了不好的最終回應」\n')
w('\n')
w('<a id="building-state-level-evaluators"></a>\n')
### 建立狀態層級評測器

w('\n')
w('每個流程狀態都有自己的評測器 prompt。以下是食譜流程的真實評測器：\n')
w('\n')
w('<a id="parserequest-evaluator"></a>\n')
#### ParseRequest 評測器

w('\n')
w(cb(1638, 1657))
w('\n')
w('<a id="plantoolcalls-evaluator"></a>\n')
#### PlanToolCalls 評測器

w('\n')
w(cb(1661, 1679))
w('\n')
w('<a id="composeresponse-evaluator"></a>\n')
#### ComposeResponse 評測器

w('\n')
w(cb(1683, 1701))
w('\n')
w('<a id="running-state-level-evaluations"></a>\n')
### 執行狀態層級評測

w('\n')
w('無論使用什麼平台，方法都是一樣的：按流程狀態查詢跨度，執行適當的評測器，並記錄結果。\n')
w('\n')
w('<a id="with-phoenix"></a>\n')
#### 使用 Phoenix

w('\n')
w(cb(1710, 1735))
w('\n')
w('<a id="with-langfuse"></a>\n')
#### 使用 Langfuse

w('\n')
w(cb(1739, 1759))
w('\n')
w('<a id="analyzing-failure-distribution"></a>\n')
### 分析失敗分佈

w('\n')
w('評測 100 條有意設置失敗的合成追蹤記錄的結果範例：\n')
w('\n')
w(cb(1763, 1778))
w('\n')
w('**關鍵洞察：** GetWebInfo 是最大的瓶頸。優先針對這裡進行優化。\n')
w('\n')
w('<a id="using-llm-to-synthesize-improvement-strategies"></a>\n')
### 使用 LLM 綜合改進策略

w('\n')
w(cb(1784, 1808))
w('\n')
w('<a id="for-pmsqas-pipeline-evaluation-without-code"></a>\n')
### 給 PM/QA：不用寫程式碼的流程評測

w('\n')
w('即使不寫程式碼，你也可以：\n')
w('\n')
w('1. **打開你的可觀測性 UI** 並按流程狀態查看追蹤記錄\n')
w('2. **篩選失敗狀態** 使用標注/分數篩選器\n')
w('3. **閱讀 LLM 評測器生成的失敗說明**\n')
w('4. **識別模式**（例如，「GenRecipeArgs 在查詢是關於烹飪技術時失敗」）\n')
w('5. **提交具體的、有數據支持的 bug**（例如，「GenRecipeArgs 在 12% 的時間裡丟失了飲食篩選條件」）\n')
w('\n')
w('---\n')
w('\n')
