import sys
orig = open("ai_evals_comprehensive_study_guide.md", encoding="utf-8").read()
orig_lines = orig.splitlines(keepends=True)
cb = lambda s, e: "".join(orig_lines[s-1:e])
out = open("ai_evals_comprehensive_study_guide.md.new", "w", encoding="utf-8")
w = out.write

w('# ── Title + Intro (lines 1-54) ──────────────────────────────────────────────')
w('<a id="ai-evals-for-engineers-pms--qas-complete-study-guide"></a>\n')
w('# 工程師、PM 與 QA 的 AI 評測完全學習指南\n')
w('\n')
w('*基於 Hamel Husain 與 Shreya Shankar 在 Maven 的課程，結合實踐範例、生產就緒程式碼，以及針對 Phoenix、Langfuse 等平台的詳細指南*\n')
w('\n')
w('**這份指南適合誰？**\n')
w('- **工程師**：正在開發 AI 驅動產品，需要系統性地評估品質\n')
w('- **產品經理（PM）**：負責產品體驗，需要主導錯誤分析\n')
w('- **QA 工程師**：需要為 AI 系統建立自動化評測管線\n')
w('- **任何人**：想學習如何評測 AI 應用程式，而不必修完整門課程\n')
w('\n')
w('**你將學到：**\n')
w('- 如何為任何 AI 應用程式設置可觀測性\n')
w('- 如何系統性地找出問題所在（錯誤分析）\n')
w('- 如何建立自動化評測器（基於程式碼的評測器與 LLM judge）\n')
w('- 如何評測 RAG 系統、多步驟管線與多輪對話\n')
w('- 如何執行生產環境評測：護欄、安全性與即時監控\n')
w('- 如何使用統計修正來補償 judge 的偏差\n')
w('- 如何形成閉環：將評測結果轉化為系統改進\n')
w('- 如何使用你選擇的可觀測性平台完成上述一切（Phoenix、Langfuse、Braintrust、LangSmith，或自建平台）\n')
w('\n')
w('**平台範例：** 本指南以 **Arize Phoenix**（開源、自架）和 **Langfuse**（開源、雲端或自架）為主要範例。方法論是平台中立的——請依你使用的工具自行調整。\n')
w('\n')
w('---\n')
w('\n')
w('<a id="table-of-contents"></a>\n')
w('## 目錄\n')
w('\n')
w('1. [AI 評測是什麼，以及為什麼你需要它們](#chapter-1)\n')
w('2. [設置可觀測性](#chapter-2)\n')
w('3. [錯誤分析：秘密武器](#chapter-3)\n')
w('4. [建立 LLM-as-a-Judge 評測器](#chapter-4)\n')
w('5. [基於程式碼的評測器](#chapter-5)\n')
w('6. [RAG 系統評測](#chapter-6)\n')
w('7. [多步驟管線評測](#chapter-7)\n')
w('8. [多輪對話評測](#chapter-8)\n')
w('9. [生產環境評測：安全性、護欄與監控](#chapter-9)\n')
w('10. [使用 judgy 進行統計修正](#chapter-10)\n')
w('11. [形成閉環：從評測到改進](#chapter-11)\n')
w('12. [人工標注最佳實踐](#chapter-12)\n')
w('13. [成本、延遲與評測擴展](#chapter-13)\n')
w('14. [實踐實施指南](#chapter-14)\n')
w('15. [常見錯誤避免指南](#chapter-15)\n')
w('16. [工具與資源](#chapter-16)\n')
w('\n')
w('**附錄：**\n')
w('- [A：PM 與 QA 詞彙表](#appendix-a)\n')
w('- [B：快速參考](#appendix-b)\n')
w('- [C：生產環境中完整的 judge prompt](#appendix-c)\n')
w('- [D：管線狀態評測器 prompt](#appendix-d)\n')
w('- [E：Judge Prompt 工程技巧](#appendix-e)\n')
w('- [F：平台方法參考（Phoenix 與 Langfuse）](#appendix-f)\n')
w('- [G：30 天學習路徑](#appendix-g)\n')
w('\n')
w('---\n')
w('\n')
w('# ── Chapter 1 (lines 55-141) ──────────────────────────────────────────────')
w('<a name="chapter-1"></a>\n')
w('<a id="chapter-1-what-are-ai-evals-and-why-you-need-them"></a>\n')
w('## Chapter 1：AI 評測是什麼，以及為什麼你需要它們\n')
w('\n')
w('<a id="simple-definition"></a>\n')
w('### 簡單的定義\n')
w('\n')
w('**評測（Evals，全稱 Evaluations）** 是用來系統性地確認 AI 應用程式是否正確運作的測試。可以把它們想像成傳統軟體的單元測試，但針對的是 AI 系統。\n')
w('\n')
w('<a id="why-everyone-needs-evals"></a>\n')
w('### 為什麼每個人都需要評測\n')
w('\n')
w('關於 AI 社群有一場爭論：有些人說「直接感受一下就好」（意思是：自己試用看看，感覺不錯就行了）。但事實是：\n')
w('\n')
w('**每個人都需要評測。** 那些說不需要評測的人，其實是在受益於別人上游做的評測。\n')
w('\n')
w('範例：如果你用 GPT-4 建立了一個程式碼助理，OpenAI 已經在大量程式碼基準測試上測試過 GPT-4。所以你可以「感受一下」。但對於大多數不是基礎模型簡單用途的應用，你需要自己的評測。\n')
w('\n')
w('<a id="the-three-core-truths-about-evals"></a>\n')
w('### 關於評測的三個核心事實\n')
w('\n')
w('1. **你無法改善你沒有量測的事物**\n')
w('   - 「有用性分數」這類通用指標無法捕捉特定問題\n')
w('   - 你需要針對應用程式的特定評測\n')
w('\n')
w('2. **錯誤分析是最重要的步驟**\n')
w('   - 比 LLM judge 更重要\n')
w('   - 比精美的可觀測性工具更重要\n')
w('   - 這才是你真正學到哪裡出了問題的地方\n')
w('\n')
w('3. **PM 與 QA 必須負責錯誤分析，而不只是工程師**\n')
w('   - 工程師知道程式碼是否運作\n')
w('   - PM 知道產品體驗是否良好\n')
w('   - QA 知道如何系統性地找出問題\n')
w('   - 你擁有領域專業知識\n')
w('   - 這是產品工作，而不只是技術工作\n')
w('\n')
w('<a id="the-ai-development-cycle-is-the-scientific-method"></a>\n')
w('### AI 開發週期就是科學方法\n')
w('\n')
w('打造卓越的 AI 產品需要嚴謹的評測流程。在許多方面，AI 開發就是科學方法：\n')
w('\n')
w('1. **觀察** - 追蹤 AI 的行為（第 2 章）\n')
w('2. **假設** - 透過錯誤分析找出問題（第 3 章）\n')
w('3. **實驗** - 建立評測器並測試變更（第 4–9 章）\n')
w('4. **量測** - 計算指標並修正偏差（第 10 章）\n')
w('5. **迭代** - 根據數據改進，而非靠直覺（第 11 章）\n')
w('\n')
w('<a id="what-can-go-wrong-without-evals"></a>\n')
w('### 沒有評測會出什麼問題？\n')
w('\n')
w('你的示範運作得很好。然後上線了：\n')
w('\n')
w('- 使用者遇到你從未想過的邊緣案例\n')
w('- 文字訊息包含錯字和不尋常的格式\n')
w('- 日期的格式與預期不同\n')
w('- AI 嘗試處理應該轉交給真人的請求\n')
w('- 小幅修改 prompt 就會讓原本運作的功能壞掉\n')
w('\n')
w('**來自真實生產資料的範例：**\n')
w('w(cb(109, 115))')
w('\n')
w('同一次互動中出現了三個不同的問題！沒有適當的日誌記錄和評測，你永遠不會發現這些模式。\n')
w('\n')
w('<a id="for-pms-why-this-is-your-job"></a>\n')
w('### 給 PM：為什麼這是你的工作\n')
w('\n')
w('**錯誤的做法：**「這是技術性的 AI 事務，讓工程師去解決就好」\n')
w('\n')
w('**正確的做法：** PM 應該主導錯誤分析，因為：\n')
w('1. 你了解使用者需求\n')
w('2. 你擁有產品品味\n')
w('3. 你擁有領域專業知識\n')
w('4. 這是披著技術外衣的產品工作\n')
w('\n')
w('**打造出最佳 AI 產品的團隊，擁有親自審閱過數百甚至數千條追蹤記錄的 PM。**\n')
w('\n')
w('<a id="for-qas-your-new-superpower"></a>\n')
w('### 給 QA：你的新超能力\n')
w('\n')
w('傳統 QA 涉及有預期輸出的測試案例。AI QA 則不同：\n')
w('1. 輸出是不確定的（相同輸入可能產生不同輸出）\n')
w('2. 「正確」往往是主觀的\n')
w('3. 邊緣案例幾乎是無限的\n')
w('4. 你需要可擴展的自動化評測器\n')
w('\n')
w('但核心的 QA 思維——系統性測試、邊緣案例思維、回歸預防——正是 AI 評測所需要的。學會評測的 QA 工程師將變得極具價值。\n')
w('\n')
w('---\n')
w('\n')
# ── Chapter 2 (lines 143-425) ──────────────────────────────────────────────
w('<a name="chapter-2"></a>\n')
w('<a id="chapter-2-setting-up-observability"></a>\n')
w('## Chapter 2：設置可觀測性\n')

w('\n')
w('<a id="what-is-a-trace"></a>\n')
w('### 什麼是追蹤記錄（Trace）？\n')

w('\n')
w('**追蹤記錄（trace）** 是 AI 在回應使用者時所做一切的完整記錄。就像詳細的日誌，顯示：\n')
w('\n')
w('1. **系統 prompt**（給 AI 的指示）\n')
w('2. **使用者訊息**（使用者的提問）\n')
w('3. **工具呼叫**（AI 嘗試使用的函式）\n')
w('4. **工具回應**（那些函式回傳的結果）\n')
w('5. **助理回應**（AI 的回覆）\n')
w('6. **所有上下文**（LLM 在做決策時看到的一切）\n')
w('\n')
w('<a id="example-of-a-complete-trace"></a>\n')
w('### 完整追蹤記錄的範例\n')

w('\n')
w(cb(159, 180))
w('\n')
w('<a id="what-information-to-capture"></a>\n')
w('### 要記錄哪些資訊\n')

w('\n')
w('**最低需求：**\n')
w('- 輸入（使用者訊息）\n')
w('- 輸出（AI 回應）\n')
w('- 時間戳記\n')
w('- 互動的唯一識別碼\n')
w('\n')
w('**建議包含：**\n')
w('- 使用的系統 prompt\n')
w('- 工具呼叫及其結果\n')
w('- 模型參數（temperature、max_tokens 等）\n')
w('- Token 數量\n')
w('- 延遲（回應時間）\n')
w('- 每次請求的成本\n')
w('\n')
w('**最佳實踐：**\n')
w('- 使用者上下文（對話歷史）\n')
w('- 發生的錯誤訊息（如有）\n')
w('- 使用的模型版本\n')
w('- 當時啟用的功能開關\n')
w('\n')
w('<a id="choosing-an-observability-platform"></a>\n')
w('### 選擇可觀測性平台\n')

w('\n')
w('| 工具 | 類型 | 最適合 | 費用 |\n')
w('|------|------|----------|------|\n')
w('| **Arize Phoenix** | 開源、自架 | 功能完整，單一 Docker 容器 | 免費 |\n')
w('| **Langfuse** | 開源、雲端或自架 | 精緻 UI，強大社群 | 免費方案 + 付費 |\n')
w('| **Braintrust** | 雲端 | 出色 UI，團隊協作 | 付費 |\n')
w('| **LangSmith** | 雲端 | LangChain 使用者 | 付費 |\n')
w('| **自行建立** | 自訂 | 學習、自訂需求 | 免費 |\n')
w('\n')
w('所有這些平台都支援相同的核心概念：追蹤記錄（traces）、跨度（spans）、資料集、評測和實驗。本指南的方法論適用於任何一個。\n')
w('\n')
w('<a id="setting-up-phoenix-open-source-self-hosted"></a>\n')
w('### 設置 Phoenix（開源、自架）\n')

w('\n')
w('Phoenix 是一個基於 OpenTelemetry 構建的開源 AI 可觀測性平台。它提供追蹤記錄、評測、資料集、實驗和 prompt 管理——完全免費。\n')
w('\n')
w('<a id="install-and-start"></a>\n')
w('#### 安裝與啟動\n')

w('\n')
w(cb(222, 226))
w('\n')
w('<a id="instrument-your-application"></a>\n')
w('#### 為你的應用程式添加儀器\n')

w('\n')
w(cb(230, 241))
w('\n')
w('<a id="your-openai-calls-are-now-traced"></a>\n')
w('#### 你的 OpenAI 呼叫現在已被追蹤\n')

w('\n')
w(cb(245, 259))
w('\n')
w('<a id="add-custom-spans"></a>\n')
w('#### 新增自訂跨度\n')

w('\n')
w(cb(263, 275))
w('\n')
w('<a id="setting-up-langfuse-open-source-cloud-or-self-hosted"></a>\n')
w('### 設置 Langfuse（開源、雲端或自架）\n')

w('\n')
w('Langfuse 提供追蹤記錄、評測、資料集、實驗和 prompt 管理。它提供託管雲端和自架選項。\n')
w('\n')
w('<a id="install-and-configure"></a>\n')
w('#### 安裝與設定\n')

w('\n')
w(cb(283, 292))
w('\n')
w('<a id="instrument-your-application-drop-in-replacement"></a>\n')
w('#### 為你的應用程式添加儀器（直接替換）\n')

w('\n')
w(cb(296, 311))
w('\n')
w('<a id="add-custom-spans-with-decorators"></a>\n')
w('#### 使用裝飾器新增自訂跨度\n')

w('\n')
w(cb(315, 329))
w('\n')
w('<a id="creating-and-managing-prompts"></a>\n')
w('### 建立與管理 Prompt\n')

w('\n')
w('兩個平台都支援有版本控制的 prompt 管理：\n')
w('\n')
w('<a id="phoenix"></a>\n')
w('#### Phoenix\n')

w('\n')
w(cb(337, 351))
w('\n')
w('<a id="langfuse"></a>\n')
w('#### Langfuse\n')

w('\n')
w(cb(355, 373))
w('\n')
w('<a id="uploading-test-datasets"></a>\n')
w('### 上傳測試資料集\n')

w('\n')
w('<a id="phoenix-1"></a>\n')
w('#### Phoenix\n')

w('\n')
w(cb(379, 398))
w('\n')
w('<a id="langfuse-1"></a>\n')
w('#### Langfuse\n')

w('\n')
w(cb(402, 416))
w('\n')
w('<a id="key-principle"></a>\n')
w('### 關鍵原則\n')

w('\n')
w('**沒有追蹤記錄，就無法進行評測。** 這是你的基礎。在做任何其他事情之前，先設置好這個。\n')
w('\n')
w('**給 PM/QA：** 你不需要編寫儀器化程式碼。請工程師設置追蹤記錄，然後使用 Web UI 以視覺化方式查看追蹤記錄。Phoenix（`localhost:6006`）和 Langfuse（`cloud.langfuse.com` 或你的自架 URL）都提供 UI，讓你無需編寫任何程式碼即可瀏覽、搜尋和標注追蹤記錄。\n')
w('\n')
w('---\n')
w('\n')
# ── Chapter 3 (lines 426-753) ──────────────────────────────────────────────
w('<a name="chapter-3"></a>\n')
w('<a id="chapter-3-error-analysis-the-secret-sauce"></a>\n')
w('## Chapter 3：錯誤分析：秘密武器\n')

w('\n')
w('<a id="what-is-error-analysis"></a>\n')
w('### 什麼是錯誤分析？\n')

w('\n')
w('錯誤分析是一個**系統性流程**，包含：\n')
w('1. 審閱追蹤記錄（AI 互動的日誌）\n')
w('2. 記錄你發現的問題\n')
w('3. 對這些問題進行分類\n')
w('4. 統計每種問題類型的發生頻率\n')
w('\n')
w('**這是**建立可靠 AI 產品**最重要的技能**。\n')
w('\n')
w('大多數團隊直接跳到建立精美的儀表板或 LLM judge。這是本末倒置的。你需要先理解哪裡出了問題，然後才能量測它。\n')
w('\n')
w('<a id="why-pms-and-qas-must-do-this-not-just-engineers"></a>\n')
w('### 為什麼 PM 與 QA 必須參與（而不只是工程師）\n')

w('\n')
w('**錯誤的做法：**\n')
w('「這是技術性的 AI 事務，讓工程師去解決就好」\n')
w('\n')
w('**正確的做法：**\n')
w('PM 與 QA 應該主導錯誤分析，因為：\n')
w('\n')
w('1. **你了解使用者需求** - 工程師不知道「連結浴室」vs「獨立浴室」對使用者是否重要\n')
w('2. **你有產品品味** - 你知道好的體驗是什麼樣子\n')
w('3. **你有領域專業知識** - 你理解商業需求\n')
w('4. **這是產品工作** - 披著技術外衣，但本質上是關於產品品質的\n')
w('\n')
w('**實際影響：**\n')
w('打造出最佳 AI 產品的團隊，擁有親自審閱過數百甚至數千條追蹤記錄的 PM。\n')
w('\n')
w('<a id="step-1-generate-diverse-test-queries"></a>\n')
w('### 步驟 1：生成多樣化的測試查詢\n')

w('\n')
w('在審閱追蹤記錄之前，你需要多樣化的測試輸入。一個強大的技術是**維度抽樣**。\n')
w('\n')
w('<a id="define-key-dimensions"></a>\n')
w('#### 定義關鍵維度\n')

w('\n')
w('找出對你的產品重要的 3-4 個維度：\n')
w('\n')
w(cb(465, 482))
w('\n')
w('<a id="generate-random-combinations"></a>\n')
w('#### 生成隨機組合\n')

w('\n')
w(cb(486, 500))
w('\n')
w('<a id="convert-tuples-to-natural-language-queries-using-an-llm"></a>\n')
w('#### 使用 LLM 將元組轉換為自然語言查詢\n')

w('\n')
w('你可以使用任何 LLM 將維度元組轉換為真實查詢。以下是一個平台中立的方法，以及一個 Phoenix 特定的批次方法：\n')
w('\n')
w('**使用任何 LLM（平台中立）：**\n')
w('\n')
w(cb(508, 530))
w('\n')
w('**使用 Phoenix（批次生成）：**\n')
w('\n')
w(cb(534, 548))
w('\n')
w('**轉換範例：**\n')
w('\n')
w('| 維度元組 | 生成的查詢 |\n')
w('|---|---|\n')
w('| vegan、Italian、dinner、beginner | 「嘿，我是新手，也是素食者。你能推薦一個簡單的義大利晚餐嗎？」 |\n')
w('| gluten-free、any、dessert、intermediate | 「我在找一個有點挑戰性的無麩質甜點」 |\n')
w('| keto、American、breakfast、advanced | 「給我一個複雜的生酮早餐食譜，美式風格」 |\n')
w('\n')
w('**給 PM/QA：** 這種維度方法確保你測試完整的使用者需求空間。沒有它，你只會測試顯而易見的案例，而錯過使用者組合意外需求的邊緣案例。\n')
w('\n')
w('<a id="step-2-review-100-traces-and-take-notes-open-coding"></a>\n')
w('### 步驟 2：審閱 100 條追蹤記錄並做筆記（開放編碼）\n')

w('\n')
w('**流程（每條追蹤記錄 30 秒）：**\n')
w('\n')
w('1. 打開你的追蹤記錄查看器（Phoenix UI、Langfuse 儀表板或任何工具）\n')
w('2. 查看第一條追蹤記錄\n')
w('3. 瀏覽它：\n')
w('   - 閱讀使用者訊息\n')
w('   - 確認 AI 是否呼叫了正確的工具\n')
w('   - 查看工具回傳了什麼\n')
w('   - 閱讀助理的回應\n')
w('   - 記錄你發現的任何問題\n')
w('\n')
w('**來自真實錯誤分析會話的筆記範例：**\n')
w('\n')
w(cb(575, 591))
w('\n')
w('**錯誤分析規則：**\n')
w('\n')
w('1. **不要試圖抓住所有問題** - 只記錄最重要的事情\n')
w('2. **不要對每條追蹤記錄爭論** - 快速思考，記下來，繼續前進\n')
w('3. **跳過系統 prompt** - 如果它通常是相同的，你不需要每次都讀\n')
w('4. **進入心流狀態** - 這應該感覺快速，而不是繁瑣\n')
w('\n')
w('**時間承諾：**\n')
w('- 第一條追蹤記錄：45 秒\n')
w('- 10 條後：每條 25 秒\n')
w('- 50 條後：每條 20 秒\n')
w('- **100 條追蹤記錄的總時間：約 45 分鐘**\n')
w('\n')
w('<a id="step-3-categorize-errors-using-axial-coding"></a>\n')
w('### 步驟 3：使用軸向編碼對錯誤進行分類\n')

w('\n')
w('現在你有 40-50 條分散在各追蹤記錄中的筆記。是時候整理它們了。\n')
w('\n')
w('這個過程稱為**「軸向編碼」**（一種源自社會學的研究方法）。你正在將相似的錯誤分組為類別。\n')
w('\n')
w('<a id="using-an-llm-to-help-discover-categories"></a>\n')
w('#### 使用 LLM 幫助發現類別\n')

w('\n')
w('匯出你的筆記，然後使用此 prompt：\n')
w('\n')
w(cb(616, 636))
w('\n')
w('**來自真實食譜機器人評測的結果範例：**\n')
w('\n')
w(cb(640, 643))
w('\n')
w('<a id="refine-categories-to-be-specific-and-actionable"></a>\n')
w('#### 細化類別以使其具體且可操作\n')

w('\n')
w('**問題：** 通用的 LLM 建議太模糊！\n')
w('\n')
w('「時間問題」——這是什麼意思？\n')
w('「品質問題」——太籠統！\n')
w('\n')
w('**更好的類別（具體且可操作）：**\n')
w('\n')
w('1. **飲食限制被忽略** - 機器人建議違反飲食限制的食材\n')
w('2. **格式錯誤** - 在 SMS 中使用 Markdown、結構錯誤\n')
w('3. **複雜度不匹配** - 食譜對於聲明的技能等級太難/太簡單\n')
w('4. **餐食類型不匹配** - 詢問早餐時卻建議晚餐\n')
w('5. **食材遺漏** - 沒有包含使用者要求的特定食材\n')
w('6. **技能等級不一致** - 對初學者使用高級技巧\n')
w('\n')
w('**你的類別需要足夠具體，以便其他人能夠用它們來標注錯誤。**\n')
w('\n')
w('<a id="step-4-label-your-errors-with-llm-assistance"></a>\n')
w('### 步驟 4：使用 LLM 協助標注錯誤\n')

w('\n')
w('此步驟適用於任何 LLM。如果你的平台支援，請使用批次處理：\n')
w('\n')
w(cb(667, 682))
w('\n')
w('<a id="step-5-count-and-prioritize"></a>\n')
w('### 步驟 5：計數並排定優先順序\n')

w('\n')
w('**統計每個類別出現的次數：**\n')
w('\n')
w(cb(688, 690))
w('\n')
w('**來自真實評測的結果範例：**\n')
w('\n')
w('| 類別 | 次數 | 百分比 |\n')
w('|----------|-------|------------|\n')
w('| 複雜度不匹配 | 2 | 22% |\n')
w('| 餐食類型不匹配 | 2 | 22% |\n')
w('| 食材遺漏 | 2 | 22% |\n')
w('| 飲食限制被忽略 | 1 | 11% |\n')
w('| 格式錯誤 | 1 | 11% |\n')
w('| 技能等級不一致 | 1 | 11% |\n')
w('\n')
w('<a id="why-this-changes-everything"></a>\n')
w('### 為什麼這改變了一切\n')

w('\n')
w('**錯誤分析之前：**\n')
w('- 你一籌莫展\n')
w('- 不知道先修什麼\n')
w('- 無法排定優先順序\n')
w('\n')
w('**錯誤分析之後：**\n')
w('- 基於頻率的清晰優先順序\n')
w('- 了解嚴重性（頻率 vs. 影響）\n')
w('- 用於與利害關係人討論的證據\n')
w('- 要建立哪些評測器的具體清單\n')
w('\n')
w('**優先順序討論範例：**\n')
w('\n')
w(cb(718, 726))
w('\n')
w('<a id="the-theoretical-saturation-concept"></a>\n')
w('### 「理論飽和」概念\n')

w('\n')
w('**何時停止審閱追蹤記錄？**\n')
w('\n')
w('在定性研究中，有一個稱為「理論飽和」的概念——當你停止發現新類型的錯誤時。\n')
w('\n')
w('- 審閱前 50 條追蹤記錄：你發現 10 種不同的錯誤類型\n')
w('- 審閱接下來 25 條：你發現 2 種新錯誤類型\n')
w('- 審閱接下來 25 條：你發現 0 種新錯誤類型\n')
w('- **在這裡停止！** 你已達到飽和\n')
w('\n')
w('如果你在 100 條之後沒有發現新模式，你不需要審閱 1000 條追蹤記錄。\n')
w('\n')
w('<a id="for-pmsqas-your-error-analysis-checklist"></a>\n')
w('### 給 PM/QA：你的錯誤分析清單\n')

w('\n')
w('1. 請工程師設置追蹤記錄（Phoenix、Langfuse 或任何工具）\n')
w('2. 打開追蹤記錄查看器 UI\n')
w('3. 瀏覽 100 條追蹤記錄，快速記錄問題\n')
w('4. 使用 LLM 將你的筆記分類為 4-6 種失敗模式\n')
w('5. 統計每種失敗模式的出現次數\n')
w('6. 同時考慮頻率和嚴重性，建立優先順序清單\n')
w('7. 向你的團隊提交有數據支持的建議\n')
w('8. 每月重複，使用新的追蹤記錄以發現新的失敗模式\n')
w('\n')
w('---\n')
w('\n')
# ── Chapter 4 (lines 754-1208) ──────────────────────────────────────────────
w('<a name="chapter-4"></a>\n')
w('<a id="chapter-4-building-llm-as-a-judge-evaluators"></a>\n')
w('## Chapter 4：建立 LLM-as-a-Judge 評測器\n')

w('\n')
w('<a id="what-is-llm-as-a-judge"></a>\n')
w('### 什麼是 LLM-as-a-Judge？\n')

w('\n')
w('**LLM judge** 是一個評估其他 AI 輸出的 AI。它讀取追蹤記錄並給分。\n')
w('\n')
w('**為什麼使用它？**\n')
w('- 自動化大規模評測\n')
w('- 提供一致的判斷\n')
w('- 比人工審閱快得多\n')
w('\n')
w('**挑戰：**\n')
w('大多數人建立的 judge 是錯的。它們會幻覺、遺漏問題，或造成虛假的信心。\n')
w('\n')
w('<a id="when-to-use-llm-as-a-judge"></a>\n')
w('### 何時使用 LLM-as-a-Judge\n')

w('\n')
w('**適合用 LLM judge：**\n')
w('- 主觀品質評估\n')
w('- 政策合規性檢查\n')
w('- 上下文理解\n')
w('- 飲食遵循\n')
w('- 語調適切性\n')
w('- 多步驟推理檢查\n')
w('\n')
w('**不適合用 LLM judge：**\n')
w('- 格式驗證（用程式碼）\n')
w('- 必填欄位檢查（用程式碼）\n')
w('- 簡單模式匹配（用程式碼）\n')
w('- 完全字串匹配（用程式碼）\n')
w('\n')
w('**經驗法則：** 如果你能用 if/else 陳述式表達，就用程式碼。如果需要判斷，就用 LLM。\n')
w('\n')
w('<a id="the-complete-llm-judge-workflow"></a>\n')
w('### 完整的 LLM Judge 工作流程\n')

w('\n')
w('建立可靠的 LLM judge 需要嚴格的 7 步驟工作流程：\n')
w('\n')
w('<a id="overview-the-pipeline"></a>\n')
w('#### 概覽：流程\n')

w('\n')
w(cb(793, 801))
w('\n')
w('<a id="step-1-generate-traces"></a>\n')
w('### 步驟 1：生成追蹤記錄\n')

w('\n')
w('在多樣化的測試查詢上執行你的 AI 系統，以建立追蹤記錄。使用你的平台的自動儀器化（見 Chapter 2）來自動捕獲一切。\n')
w('\n')
w('<a id="step-2-label-ground-truth-data"></a>\n')
w('### 步驟 2：標注基準真值資料\n')

w('\n')
w('將 150-200 條追蹤記錄標注為 PASS 或 FAIL。你可以手動（最準確）或使用強大的 LLM 來完成：\n')
w('\n')
w(cb(811, 830))
w('\n')
w('<a id="step-3-split-data-train--dev--test"></a>\n')
w('### 步驟 3：分割資料（Train / Dev / Test）\n')

w('\n')
w('這一步很關鍵，經常被跳過！你需要三個獨立的集合：\n')
w('\n')
w('- **Train（約 15%）：** 用於為你的 judge prompt 選取少樣本（few-shot）範例\n')
w('- **Dev（約 40%）：** 用於迭代和改進你的 judge prompt\n')
w('- **Test（約 45%）：** 僅使用一次，用於最終的無偏評估\n')
w('\n')
w(cb(840, 856))
w('\n')
w('<a id="step-4-develop-your-judge-prompt"></a>\n')
w('### 步驟 4：開發你的 Judge Prompt\n')

w('\n')
w('一個好的 judge prompt 包含四個部分：\n')
w('\n')
w('<a id="part-1-task-definition"></a>\n')
w('#### Part 1：任務定義\n')

w('\n')
w(cb(866, 879))
w('\n')
w('<a id="part-2-criterion-definition"></a>\n')
w('#### Part 2：標準定義\n')

w('\n')
w(cb(883, 891))
w('\n')
w('<a id="part-3-few-shot-examples"></a>\n')
w('#### Part 3：少樣本範例\n')

w('\n')
w(cb(896, 915))
w('\n')
w('<a id="part-4-output-format"></a>\n')
w('#### Part 4：輸出格式\n')

w('\n')
w(cb(919, 928))
w('\n')
w('<a id="why-binary-scores-work-best"></a>\n')
w('### 為什麼二元分數效果最好\n')

w('\n')
w('**有些人想要 1-5 等級或百分比。不要這樣做。**\n')
w('\n')
w('**使用二元（PASS/FAIL）：**\n')
w('- 只需要驗證兩件事\n')
w('- 決策邊界清晰\n')
w('- 更容易除錯\n')
w('- 更易向利害關係人解釋\n')
w('\n')
w('**使用 1-5 等級：**\n')
w('- 需要驗證每個分數是否一致\n')
w('- 2 和 3 之間的差別是什麼？\n')
w('- 5 倍的驗證工作量\n')
w('- 商業決策本就是二元的\n')
w('\n')
w('**記住：** 你要麼修復某個問題，要麼不修復。要麼壞掉，要麼沒有。\n')
w('\n')
w('<a id="step-5-validate-on-dev-set"></a>\n')
w('### 步驟 5：在 Dev 集合上驗證\n')

w('\n')
w('在 Dev 集合上執行你的 judge 並與基準真值比較。以下是各平台的作法：\n')
w('\n')
w('<a id="evaluator-functions-platform-agnostic"></a>\n')
w('#### 評測器函式（平台無關）\n')

w('\n')
w(cb(954, 978))
w('\n')
w('<a id="running-the-experiment"></a>\n')
w('#### 執行實驗\n')

w('\n')
w(cb(984, 1013))
w('\n')
w('<a id="the-metrics-that-actually-matter"></a>\n')
w('### 真正重要的指標\n')

w('\n')
w('**大多數人只看「一致性（agreement）」：**\n')
w('\n')
w(cb(1019, 1022))
w('\n')
w('**為什麼這具有誤導性：**\n')
w('\n')
w('如果失敗只發生 10% 的時間，一個總是說「pass」的 judge 因為完全無用而得到 90% 的準確率！\n')
w('\n')
w('**你真正需要的兩個指標：**\n')
w('\n')
w('<a id="1-tpr-true-positive-rate---recall"></a>\n')
w('#### 1. TPR（真正例率）- 召回率\n')

w('\n')
w('**「當實際上是 PASS 時，judge 多常正確地說 PASS？」**\n')
w('\n')
w(cb(1034, 1036))
w('\n')
w('<a id="2-tnr-true-negative-rate---specificity"></a>\n')
w('#### 2. TNR（真負例率）- 特異性\n')

w('\n')
w('**「當實際上是 FAIL 時，judge 多常正確地說 FAIL？」**\n')
w('\n')
w(cb(1042, 1044))
w('\n')
w('<a id="real-results-why-iteration-matters"></a>\n')
w('### 真實結果：為什麼迭代很重要\n')

w('\n')
w('**謹慎的 prompt 迭代後（生產品質的 judge）：**\n')
w('\n')
w(cb(1050, 1058))
w('\n')
w('<a id="prompt-iteration-tips"></a>\n')
w('### Prompt 迭代技巧\n')

w('\n')
w(cb(1062, 1067))
w('\n')
w('**關鍵洞察：**\n')
w('\n')
w('1. **從 Train 集合中選取 FP/FN 作為少樣本範例** - 使用你的 judge 在 Dev 集合中搞錯的例子\n')
w('2. **要具體說明什麼是 FAIL** - 給出每個限制的精確違反範例\n')
w('3. **以 FAIL 案例開頭你的少樣本範例** - LLM 更注意最近的例子\n')
w('4. **每個飲食限制使用不同的 judge** - 更好地控制 TPR/TNR\n')
w('5. **使用 temperature=0** - 確保一致性\n')
w('6. **為什麼要使用強大的 LLM（GPT-4o、Claude 等）** - 品質 > 成本用於評測\n')
w('7. **然後在 Test 集合上測試一次以獲得最終的無偏指標**\n')
w('\n')
w('<a id="step-6-final-evaluation-on-test-set"></a>\n')
w('### 步驟 6：在 Test 集合上進行最終評估\n')

w('\n')
w('一旦你的 judge 在 Dev 上表現良好，在 Test 集合上執行一次：\n')
w('\n')
w(cb(1106, 1118))
w('\n')
w('<a id="step-7-run-on-all-traces-at-scale"></a>\n')
w('### 步驟 7：大規模執行所有追蹤記錄\n')

w('\n')
w('一旦驗證完成，在所有生產追蹤記錄上執行你的 judge：\n')
w('\n')
w(cb(1126, 1167))
w('\n')
w('**結果範例：** 在 1000 條追蹤記錄上的原始通過率 = 84.4%\n')
w('\n')
w('但這個原始比率沒有考慮 judge 的錯誤。Chapter 10 介紹如何使用  函式庫來修正這個問題。\n')
w('\n')
w('<a id="llm-as-judge-across-different-domains"></a>\n')
w('### LLM-as-Judge 跨不同領域\n')

w('\n')
w('食譜機器人只是一個例子。以下是相同方法論如何應用於其他領域：\n')
w('\n')
w(cb(1178, 1203))
w('\n')
w('結構始終相同：定義標準、撰寫 PASS/FAIL 定義、添加少樣本範例、用 TPR/TNR 驗證。\n')
w('\n')
w('---\n')
w('\n')
# ── Chapter 5 (lines 1209-1386) ──────────────────────────────────────────────
w('<a name="chapter-5"></a>\n')
w('<a id="chapter-5-code-based-evaluators"></a>\n')
w('## Chapter 5：程式碼型評測器\n')

w('\n')
w('<a id="what-are-code-based-evals"></a>\n')
w('### 什麼是程式碼型 Eval？\n')

w('\n')
w('程式碼型 eval 是你用**程式語言**（如 Python）撰寫的**檢查**，用於驗證 AI 輸出的特定客觀屬性。\n')
w('\n')
w('<a id="when-to-use-code-based-evals"></a>\n')
w('### 何時使用程式碼型 Eval\n')

w('\n')
w('**當你不需要呼叫 LLM 就能測試某件事時，使用程式碼：**\n')
w('\n')
w('1. **格式驗證** - Markdown 是否出現在文字訊息中？\n')
w('2. **必填欄位檢查** - AI 是否包含所有必要資訊？\n')
w('3. **工具呼叫驗證** - AI 是否呼叫了正確的工具？\n')
w('4. **回應長度限制** - 回應是否在 500 字元以下？\n')
w('5. **禁止內容模式** - 是否有 PII（電子郵件、電話號碼）？\n')
w('\n')
w('<a id="example-1-check-for-markdown-in-text-messages"></a>\n')
w('### 範例 1：檢查文字訊息中是否有 Markdown\n')

w('\n')
w(cb(1228, 1254))
w('\n')
w('<a id="example-2-validate-tool-calls"></a>\n')
w('### 範例 2：驗證工具呼叫\n')

w('\n')
w(cb(1258, 1287))
w('\n')
w('<a id="example-3-validate-required-information-in-tour-confirmations"></a>\n')
w('### 範例 3：驗證行程確認中的必要資訊\n')

w('\n')
w(cb(1292, 1323))
w('\n')
w('<a id="benefits-of-code-based-evals"></a>\n')
w('### 程式碼型 Eval 的優點\n')

w('\n')
w('1. **快速** - 無需 API 呼叫，立即得到結果\n')
w('2. **便宜** - 不消耗 token\n')
w('3. **確定性** - 相同輸入始終產生相同輸出\n')
w('4. **易於除錯** - 堆疊追蹤、中斷點都能正常運作\n')
w('5. **無幻覺** - 程式碼完全按照你的指示執行\n')
w('\n')
w('<a id="combining-code-based-and-llm-based-evals"></a>\n')
w('### 結合程式碼型與 LLM 型 Eval\n')

w('\n')
w('完整的 eval 套件通常包含：\n')
w('- **2-3 個程式碼型 eval** 用於客觀檢查\n')
w('- **1-2 個 LLM 型 eval** 用於主觀判斷\n')
w('\n')
w(cb(1339, 1348))
w('\n')
w('<a id="testing-your-code-based-evals"></a>\n')
w('### 測試你的程式碼型 Eval\n')

w('\n')
w('**始終用已知的好案例和壞案例測試你的 eval：**\n')
w('\n')
w(cb(1354, 1383))
w('\n')
w('---\n')
w('\n')
# ── Chapter 6 (lines 1387-1589) ──────────────────────────────────────────────
w('<a name="chapter-6"></a>\n')
w('<a id="chapter-6-rag-system-evaluation"></a>\n')
w('## Chapter 6：RAG 系統評測\n')

w('\n')
w('<a id="what-is-rag"></a>\n')
w('### 什麼是 RAG？\n')

w('\n')
w('**RAG（檢索增強生成）** 意味著你的 AI：\n')
w('1. **檢索**資料庫中的相關資訊\n')
w('2. **使用該資訊**來生成回應\n')
w('\n')
w('<a id="why-rag-needs-special-evaluation"></a>\n')
w('### 為什麼 RAG 需要特殊評測\n')

w('\n')
w('RAG 有**兩種失敗模式：**\n')
w('\n')
w('1. **檢索失敗** - 找不到正確資訊\n')
w('2. **生成失敗** - 使用資訊的方式錯誤\n')
w('\n')
w('你需要**分開評測兩者**，才能知道問題出在哪裡。\n')
w('\n')
w('<a id="building-a-bm25-retrieval-engine"></a>\n')
w('### 建立 BM25 檢索引擎\n')

w('\n')
w('在為特定領域（如食譜）建立關鍵字檢索時，關鍵洞察是：**你的分詞器（tokenizer）很重要**。\n')
w('\n')
w('<a id="custom-tokenizer-for-domain-specific-content"></a>\n')
w('#### 針對特定領域內容的自訂分詞器\n')

w('\n')
w(cb(1411, 1429))
w('\n')
w('**為什麼這很重要：** 標準分詞器會去除數字。但在食譜中，「375」（溫度）、「9x13」（烤盤尺寸）和「1/2」（量測單位）是關鍵的搜尋詞。\n')
w('\n')
w('<a id="generating-synthetic-queries-for-rag-testing"></a>\n')
w('### 為 RAG 測試生成合成查詢\n')

w('\n')
w('與其手動撰寫測試查詢，不如使用 LLM 生成依賴文件中特定事實的查詢：\n')
w('\n')
w(cb(1437, 1449))
w('\n')
w('這會生成如下查詢：\n')
w('- 「薑餅城堡餅乾應該烤什麼溫度？」（顯著事實：「350 degrees F for 8-10 minutes」）\n')
w('- 「麵包麵團應該發酵多久？」（顯著事實：「rise for 1 hour until doubled」）\n')
w('\n')
w('（顯著事實）就是你的基準真值——你知道哪個食譜有答案。\n')
w('\n')
w('<a id="evaluating-retrieval-quality"></a>\n')
w('### 評測檢索品質\n')

w('\n')
w('<a id="recallk"></a>\n')
w('#### Recall@K\n')

w('\n')
w('「正確食譜是否出現在前 K 個結果中？」\n')
w('\n')
w(cb(1463, 1480))
w('\n')
w('<a id="mean-reciprocal-rank-mrr"></a>\n')
w('#### 平均倒數排名（MRR）\n')

w('\n')
w('「如果找到了，它的排名有多高？」\n')
w('\n')
w(cb(1486, 1497))
w('\n')
w('<a id="running-retrieval-experiments"></a>\n')
w('### 執行檢索實驗\n')

w('\n')
w(cb(1503, 1539))
w('\n')
w('<a id="diagnosing-rag-failures"></a>\n')
w('### 診斷 RAG 失敗\n')

w('\n')
w('當 RAG 測試失敗時，診斷**失敗點**：\n')
w('\n')
w(cb(1545, 1568))
w('\n')
w('<a id="improving-rag-performance"></a>\n')
w('### 改善 RAG 效能\n')

w('\n')
w('**當檢索失敗時：**\n')
w('1. 嘗試不同的分塊策略\n')
w('2. 添加 metadata 篩選\n')
w('3. 使用混合搜尋（關鍵字 + 語義）\n')
w('4. 實現查詢擴展\n')
w('5. 嘗試重排序模型\n')
w('6. 使用特定領域分詞器（如上面的數字保留版本）\n')
w('\n')
w('**當生成失敗時：**\n')
w('1. 改進系統 prompt\n')
w('2. 添加少樣本範例\n')
w('3. 使用思維鏈（chain-of-thought）提示\n')
w('4. 添加明確的依據指示\n')
w('5. 實現引用要求\n')
w('\n')
w('---\n')
w('\n')
# ── Chapter 7 (lines 1589-1840) ──────────────────────────────────────────────
w('<a name="chapter-7"></a>\n')
w('<a id="chapter-7-multi-step-pipeline-evaluation"></a>\n')
w('## Chapter 7：多步驟流程評測\n')

w('\n')
w('<a id="what-is-a-multi-step-pipeline"></a>\n')
w('### 什麼是多步驟流程？\n')

w('\n')
w('**多步驟流程**是指你的 AI 將任務分解為幾個階段，每個階段執行特定工作。\n')
w('\n')
w('<a id="the-7-state-recipe-bot-pipeline"></a>\n')
w('### 7 狀態食譜機器人流程\n')

w('\n')
w('以下是食譜助理的完整 7 狀態流程範例：\n')
w('\n')
w(cb(1600, 1619))
w('\n')
w('<a id="why-state-level-evaluation-matters"></a>\n')
w('### 為什麼狀態層級評測很重要\n')

w('\n')
w('**問題：** 如果你的流程失敗，失敗在哪裡？\n')
w('\n')
w('沒有狀態層級 eval，你只知道：\n')
w('- 「系統產生了一個不好的回應」\n')
w('\n')
w('有了狀態層級 eval，你就知道：\n')
w('- 「GenRecipeArgs 狀態丟失了燕麥篩選條件」\n')
w('- 「這導致 GetRecipes 返回了錯誤的食譜」\n')
w('- 「從而產生了不好的最終回應」\n')
w('\n')
w('<a id="building-state-level-evaluators"></a>\n')
w('### 建立狀態層級評測器\n')

w('\n')
w('每個流程狀態都有自己的評測器 prompt。以下是食譜流程的真實評測器：\n')
w('\n')
w('<a id="parserequest-evaluator"></a>\n')
w('#### ParseRequest 評測器\n')

w('\n')
w(cb(1638, 1657))
w('\n')
w('<a id="plantoolcalls-evaluator"></a>\n')
w('#### PlanToolCalls 評測器\n')

w('\n')
w(cb(1661, 1679))
w('\n')
w('<a id="composeresponse-evaluator"></a>\n')
w('#### ComposeResponse 評測器\n')

w('\n')
w(cb(1683, 1701))
w('\n')
w('<a id="running-state-level-evaluations"></a>\n')
w('### 執行狀態層級評測\n')

w('\n')
w('無論使用什麼平台，方法都是一樣的：按流程狀態查詢跨度，執行適當的評測器，並記錄結果。\n')
w('\n')
w('<a id="with-phoenix"></a>\n')
w('#### 使用 Phoenix\n')

w('\n')
w(cb(1710, 1735))
w('\n')
w('<a id="with-langfuse"></a>\n')
w('#### 使用 Langfuse\n')

w('\n')
w(cb(1739, 1759))
w('\n')
w('<a id="analyzing-failure-distribution"></a>\n')
w('### 分析失敗分佈\n')

w('\n')
w('評測 100 條有意設置失敗的合成追蹤記錄的結果範例：\n')
w('\n')
w(cb(1763, 1778))
w('\n')
w('**關鍵洞察：** GetWebInfo 是最大的瓶頸。優先針對這裡進行優化。\n')
w('\n')
w('<a id="using-llm-to-synthesize-improvement-strategies"></a>\n')
w('### 使用 LLM 綜合改進策略\n')

w('\n')
w(cb(1784, 1808))
w('\n')
w('<a id="for-pmsqas-pipeline-evaluation-without-code"></a>\n')
w('### 給 PM/QA：不用寫程式碼的流程評測\n')

w('\n')
w('即使不寫程式碼，你也可以：\n')
w('\n')
w('1. **打開你的可觀測性 UI** 並按流程狀態查看追蹤記錄\n')
w('2. **篩選失敗狀態** 使用標注/分數篩選器\n')
w('3. **閱讀 LLM 評測器生成的失敗說明**\n')
w('4. **識別模式**（例如，「GenRecipeArgs 在查詢是關於烹飪技術時失敗」）\n')
w('5. **提交具體的、有數據支持的 bug**（例如，「GenRecipeArgs 在 12% 的時間裡丟失了飲食篩選條件」）\n')
w('\n')
w('---\n')
w('\n')
w('<a name="chapter-11"></a>\n')
w('<a id="chapter-11-closing-the-loop--from-evals-to-improvements"></a>\n')
w('## Chapter 11：閉環——從 Eval 到改進\n')
w('\n')
w('<a id="the-most-common-failure-measuring-without-acting"></a>\n')
w('### 最常見的失敗：量測卻不行動\n')
w('\n')
w('許多團隊建立了出色的 eval 套件，卻從未系統性地利用結果來改進系統。Eval 只有在推動行動時才有價值。\n')
w('\n')
w('<a id="the-improvement-cycle"></a>\n')
w('### 改進循環\n')
w('\n')
w(cb(2160, 2166))
w('\n')
w('<a id="root-causing-failures"></a>\n')
w('### 追溯失敗根因\n')
w('\n')
w('當你的 eval 識別出失敗時，問問**失敗發生在流程的哪個環節**：\n')
w('\n')
w('| 失敗位置 | 症狀 | 典型修復方法 |\n')
w('|---|---|---|\n')
w('| **系統 prompt** | 語調錯誤、功能缺失、政策違規 | 編輯 prompt、添加範例、添加限制 |\n')
w('| **檢索** | 文件錯誤、上下文缺失 | 更好的分塊、重排序、查詢擴展 |\n')
w('| **工具呼叫** | 選擇了錯誤工具、參數錯誤 | 改進工具描述、添加驗證 |\n')
w('| **生成** | 幻覺、格式錯誤、忽略上下文 | 少樣本範例、結構化輸出、temperature 調整 |\n')
w('| **後處理** | 截斷、編碼問題、格式錯誤 | 修復解析程式碼、添加驗證 |\n')
w('\n')
w('<a id="regression-testing"></a>\n')
w('### 回歸測試\n')
w('\n')
w('每次你修復某個問題，都可能破壞其他東西。設置回歸測試：\n')
w('\n')
w(cb(2184, 2215))
w('\n')
w('<a id="model-comparison-with-evals"></a>\n')
w('### 使用 Eval 進行模型比較\n')
w('\n')
w('當評估是否切換模型時（例如 GPT-4o vs. Claude vs. Gemini）：\n')
w('\n')
w(cb(2221, 2228))
w('\n')
w('<a id="for-pms-the-improvement-playbook"></a>\n')
w('### 給 PM：改進手冊\n')
w('\n')
w('每個 eval 週期後，建立一份簡單的報告：\n')
w('\n')
w(cb(2234, 2246))
w('\n')
w('---\n')
w('\n')
w('<a name="chapter-12"></a>\n')
w('<a id="chapter-12-human-annotation-best-practices"></a>\n')
w('## Chapter 12：人工標注最佳實踐\n')
w('\n')
w('<a id="when-manual-labels-beat-llm-labels"></a>\n')
w('### 人工標籤何時優於 LLM 標籤\n')
w('\n')
w('- **模糊案例**——即使專家也不同意的情況：你需要記錄那種分歧\n')
w('- **高風險領域**（醫療、法律、金融）：錯誤有真實後果\n')
w('- **新的失敗模式**：你的 LLM judge 尚未學會偵測的\n')
w('- **基準真值校準**：即使你大規模使用 LLM 標注，也需手動驗證一個樣本\n')
w('\n')
w('<a id="inter-annotator-agreement"></a>\n')
w('### 標注者間的一致性\n')
w('\n')
w('如果兩個人對同一標籤有異議，你的 eval 標準還不夠清晰。\n')
w('\n')
w('**流程：**\n')
w('1. 讓 2-3 人獨立標注同樣的 50 條追蹤記錄\n')
w('2. 計算一致率（他們同意的百分比）\n')
w('3. 如果一致率 < 80%，你的標準需要更具體\n')
w('4. 討論分歧、更新標準、重新標注\n')
w('\n')
w(cb(2270, 2288))
w('\n')
w('<a id="label-quality--label-quantity"></a>\n')
w('### 標籤品質 > 標籤數量\n')
w('\n')
w('**50 個高品質標籤勝過 500 個雜亂標籤。** 投入時間在：\n')
w('1. 有範例的清晰書面標注指南\n')
w('2. 邊緣案例文件（「如果你看到 X，就標注為 Y，因為...」）\n')
w('3. 標注者討論分歧的定期校準會議\n')
w('\n')
w('<a id="for-pmsqas-you-are-the-best-labelers"></a>\n')
w('### 給 PM/QA：你們是最好的標注者\n')
w('\n')
w('PM 和 QA 通常比工程師產生更好的標籤，因為：\n')
w('- 你知道好的使用者體驗是什麼樣子\n')
w('- 你了解產品的政策和限制\n')
w('- 你從使用者的角度思考，而不是從程式碼的角度\n')
w('\n')
w('---\n')
w('\n')
w('<a name="chapter-13"></a>\n')
w('<a id="chapter-13-cost-latency--scaling-evals"></a>\n')
w('## Chapter 13：成本、延遲與擴展 Eval\n')
w('\n')
w('<a id="the-cost-problem"></a>\n')
w('### 成本問題\n')
w('\n')
w('在 10,000 條追蹤記錄上執行 GPT-4o 作為 judge 很昂貴。以下是管理成本的方法：\n')
w('\n')
w('<a id="strategy-1-use-cheaper-models-for-judges"></a>\n')
w('### 策略 1：為 Judge 使用更便宜的模型\n')
w('\n')
w('不是每個 eval 都需要最好的模型：\n')
w('\n')
w('| Judge 模型 | 每 1K 條追蹤記錄費用 | 使用時機 |\n')
w('|---|---|---|\n')
w('| GPT-4o / Claude Opus | ~$5-15 | 複雜主觀判斷、安全關鍵 |\n')
w('| GPT-4o-mini / Claude Haiku | ~$0.50-1.50 | 清晰標準、定義明確的評分標準 |\n')
w('| 程式碼型 | $0 | 格式檢查、模式匹配、驗證 |\n')
w('\n')
w('**提示：** 從強大的模型開始，驗證你的 judge prompt，然後測試更便宜的模型是否給出相似的 TPR/TNR。通常是可以的。\n')
w('\n')
w('<a id="strategy-2-sample-instead-of-exhaustive"></a>\n')
w('### 策略 2：抽樣而非窮舉\n')
w('\n')
w('你不需要評測每一條追蹤記錄：\n')
w('\n')
w(cb(2329, 2339))
w('\n')
w('<a id="strategy-3-tiered-evaluation"></a>\n')
w('### 策略 3：分層評測\n')
w('\n')
w('在所有追蹤記錄上執行便宜的 eval，在樣本上執行昂貴的 eval：\n')
w('\n')
w(cb(2345, 2356))
w('\n')
w('<a id="strategy-4-cache-duplicate-evaluations"></a>\n')
w('### 策略 4：快取重複評測\n')
w('\n')
w('如果相同輸入出現多次，快取 eval 結果：\n')
w('\n')
w(cb(2362, 2372))
w('\n')
w('<a id="latency-considerations-for-real-time-guardrails"></a>\n')
w('### 即時護欄的延遲考量\n')
w('\n')
w('| 檢查類型 | 典型延遲 | 適合即時？ |\n')
w('|---|---|---|\n')
w('| 正規表示式/程式碼檢查 | <1ms | 是 |\n')
w('| 嵌入相似度 | 10-50ms | 是 |\n')
w('| 小型 LLM（Haiku 等級）| 200-500ms | 勉強（增加明顯延遲）|\n')
w('| 大型 LLM（GPT-4o 等級）| 1-3s | 否（僅離線使用）|\n')
w('\n')
w('---\n')
w('\n')
w('<a name="chapter-14"></a>\n')
w('<a id="chapter-14-practical-implementation-guide"></a>\n')
w('## Chapter 14：實際實施指南\n')
w('\n')
w('<a id="your-first-two-weeks-with-evals"></a>\n')
w('### 你的第一個 Eval 兩週計畫\n')
w('\n')
w('<a id="week-1-foundation"></a>\n')
w('### 第 1 週：基礎\n')
w('\n')
w('<a id="day-1-2-set-up-logging-4-hours"></a>\n')
w('#### 第 1-2 天：設置日誌記錄（4 小時）\n')
w('\n')
w('**目標：** 捕獲每次 AI 互動的追蹤記錄。\n')
w('\n')
w('選擇你的平台並進行設置：\n')
w('\n')
w('**Phoenix：**\n')
w(cb(2399, 2402))
w('\n')
w('**Langfuse：**\n')
w(cb(2405, 2408))
w('\n')
w('然後為你的應用程式添加儀器（完整範例見 Chapter 2）。\n')
w('\n')
w('**交付物：** 每次 AI 互動都被記錄並可在你的可觀測性 UI 中看到。\n')
w('\n')
w('<a id="day-3-manual-error-analysis-3-hours"></a>\n')
w('#### 第 3 天：手動錯誤分析（3 小時）\n')
w('\n')
w('**目標：** 審閱 100 條追蹤記錄並做筆記。\n')
w('\n')
w('**交付物：** 來自 100 條追蹤記錄的 40-50 條錯誤筆記。\n')
w('\n')
w('<a id="day-4-categorize-errors-2-hours"></a>\n')
w('#### 第 4 天：對錯誤進行分類（2 小時）\n')
w('\n')
w('**目標：** 將你的筆記分組為 5-6 個類別。\n')
w('\n')
w('**交付物：** 有頻率數據的優先排序故障清單。\n')
w('\n')
w('<a id="day-5-7-build-your-first-eval-6-hours"></a>\n')
w('#### 第 5-7 天：建立你的第一個 Eval（6 小時）\n')
w('\n')
w('**目標：** 建立一個程式碼型 eval 和一個 LLM judge。\n')
w('\n')
w('**交付物：** 兩個可在新追蹤記錄上執行的有效 eval。\n')
w('\n')
w('<a id="week-2-automation-and-monitoring"></a>\n')
w('### 第 2 週：自動化與監控\n')
w('\n')
w('<a id="day-8-9-automate-eval-runs"></a>\n')
w('#### 第 8-9 天：自動化 Eval 執行\n')
w('\n')
w(cb(2456, 2475))
w('\n')
w('<a id="day-10-11-set-up-alerts"></a>\n')
w('#### 第 10-11 天：設置警報\n')
w('\n')
w(cb(2479, 2483))
w('\n')
w('<a id="day-12-14-dashboard"></a>\n')
w('#### 第 12-14 天：儀表板\n')
w('\n')
w('使用你的平台內建 UI（Phoenix 或 Langfuse 都有儀表板），或使用 eval 結果建立一個簡單的儀表板。\n')
w('\n')
w('<a id="ongoing-30-minutes-per-week"></a>\n')
w('### 持續進行：每週 30 分鐘\n')
w('\n')
w('**每個星期一（15 分鐘）：**\n')
w('1. 檢查你的可觀測性 UI 是否有異常\n')
w('2. 審閱上週的任何警報\n')
w('3. 記錄模式\n')
w('\n')
w('**每個月（2 小時）：**\n')
w('1. 對 50 條新追蹤記錄進行錯誤分析\n')
w('2. 尋找新的失敗模式\n')
w('3. 如需要，添加新的 eval\n')
w('4. 廢除從不觸發的 eval\n')
w('\n')
w('**重大變更後（1 小時）：**\n')
w('1. 執行完整的 eval 套件\n')
w('2. 與基準進行比較\n')
w('3. 調查任何回歸\n')
w('\n')
w('---\n')
w('\n')
w('<a name="chapter-15"></a>\n')
w('<a id="chapter-15-common-mistakes-to-avoid"></a>\n')
w('## Chapter 15：要避免的常見錯誤\n')
w('\n')
w('<a id="mistake-1-skipping-error-analysis"></a>\n')
w('### 錯誤 #1：跳過錯誤分析\n')
w('\n')
w('**人們的做法：** 直接跳到建立 LLM judge 或儀表板。\n')
w('**為什麼是錯的：** 你還不知道要量測什麼。\n')
w('**修復：** 始終從錯誤分析開始。花真實時間審閱追蹤記錄。\n')
w('\n')
w('<a id="mistake-2-using-only-agreement-for-validation"></a>\n')
w('### 錯誤 #2：僅使用一致性進行驗證\n')
w('\n')
w('**人們的做法：**「我的 judge 與人類有 90% 的一致性，發布！」\n')
w('**修復：** 始終分別計算 TPR 和 TNR。兩者都必須高。\n')
w('\n')
w('<a id="mistake-3-pmqa-delegates-error-analysis"></a>\n')
w('### 錯誤 #3：PM/QA 委託錯誤分析\n')
w('\n')
w('**人們的做法：**「這是技術性的，讓工程師去審閱日誌」\n')
w('**修復：** PM 和 QA 必須進行錯誤分析。這是核心的產品/品質工作。\n')
w('\n')
w('<a id="mistake-4-not-splitting-data-traindevtest"></a>\n')
w('### 錯誤 #4：不分割資料（Train/Dev/Test）\n')
w('\n')
w('**人們的做法：** 使用所有標注資料來建立和測試 judge。\n')
w('**修復：** 使用 15%/40%/45% 分割。在最終評估之前永遠不要碰 Test 集合。\n')
w('\n')
w('<a id="mistake-5-not-doing-evals-until-after-launch"></a>\n')
w('### 錯誤 #5：不在發布前進行 Eval\n')
w('\n')
w('**修復：** 在建立產品的同時建立 eval，而不是之後。\n')
w('\n')
w('<a id="mistake-6-building-too-many-evals"></a>\n')
w('### 錯誤 #6：建立太多 Eval\n')
w('\n')
w('**修復：** 從 2-3 個最大問題的 eval 開始。僅在需要時添加更多。\n')
w('**規則：** 如果一個 eval 在 3 個月內沒有觸發，刪除它。\n')
w('\n')
w('<a id="mistake-7-low-tnr-ignoring-false-positives"></a>\n')
w('### 錯誤 #7：TNR 低（忽視誤報）\n')
w('\n')
w('**修復：** TPR 和 TNR 都必須高。低 TNR 意味著 eval 無用。\n')
w('\n')
w('<a id="mistake-8-not-testing-the-evals-themselves"></a>\n')
w('### 錯誤 #8：不測試 Eval 本身\n')
w('\n')
w('**修復：** 在部署之前用已知的好案例和壞案例測試你的 eval。\n')
w('\n')
w('<a id="mistake-9-copy-pasting-eval-prompts"></a>\n')
w('### 錯誤 #9：複製貼上 Eval Prompt\n')
w('\n')
w('**修復：** 撰寫針對**你的**產品、**你的**政策、**你的**使用者的 eval。\n')
w('\n')
w('<a id="mistake-10-not-versioning-system-prompts"></a>\n')
w('### 錯誤 #10：不對系統 Prompt 進行版本控制\n')
w('\n')
w('**修復：** 使用你的平台的 prompt 管理（Phoenix、Langfuse 等）對 prompt 進行版本控制。\n')
w('\n')
w('<a id="mistake-11-not-correcting-for-judge-bias"></a>\n')
w('### 錯誤 #11：不修正 Judge 偏差\n')
w('\n')
w('**修復：** 使用 judgy 修正 judge 錯誤，並報告信賴區間。\n')
w('\n')
w('<a id="mistake-12-over-engineering-early"></a>\n')
w('### 錯誤 #12：過早過度工程化\n')
w('\n')
w('**修復：** 從簡單開始。CSV + Python 腳本 + 任何可觀測性工具。只有在簡單方式不再適用時才添加複雜性。\n')
w('\n')
w('---\n')
w('\n')
w('<a name="chapter-16"></a>\n')
w('<a id="chapter-16-tools-and-resources"></a>\n')
w('## Chapter 16：工具與資源\n')
w('\n')
w('<a id="observability-platforms"></a>\n')
w('### 可觀測性平台\n')
w('\n')
w('| 工具 | 類型 | 最適合 | 費用 |\n')
w('|------|------|----------|------|\n')
w('| **Arize Phoenix** | 開源、自架 | 單一 Docker 容器，內建完整 eval 套件 | 免費 |\n')
w('| **Langfuse** | 開源、雲端或自架 | 精緻 UI，強大社群，主流公司採用 | 免費方案 + 付費 |\n')
w('| **Braintrust** | 雲端 | 出色 UI，團隊協作 | 付費 |\n')
w('| **LangSmith** | 雲端 | LangChain 使用者 | 付費 |\n')
w('| **自行建立** | 自訂 | 學習、自訂需求 | 免費 |\n')
w('\n')
w('<a id="eval-frameworks"></a>\n')
w('### Eval 框架\n')
w('\n')
w('- **Phoenix Evals** (`arize-phoenix-evals`) - 內建於 Phoenix，`llm_generate` 和 `llm_classify`\n')
w('- **Langfuse Evals** - 內建 LLM-as-Judge，透過 SDK 自訂評測器\n')
w('- **Simple Evals**（OpenAI）- 輕量級模型評分 eval\n')
w('- **Ragas** - 專門用於 RAG 評測\n')
w('- **DeepEval** - 綜合 eval 框架\n')
w('\n')
w('<a id="key-libraries"></a>\n')
w('### 關鍵函式庫\n')
w('\n')
w('- **judgy** - LLM judge 的統計偏差修正：[github.com/ai-evals-course/judgy](https://github.com/ai-evals-course/judgy)\n')
w('- **rank_bm25** - 用於 RAG 系統的 BM25 檢索\n')
w('- **litellm** - 統一的 LLM API 介面\n')
w('\n')
w('<a id="key-principles-revisited"></a>\n')
w('### 關鍵原則（重溫）\n')
w('\n')
w('1. **從簡單開始** - 不要過度工程化\n')
w('2. **錯誤分析優先** - 始終\n')
w('3. **PM 和 QA 必須參與** - 這是產品/品質工作\n')
w('4. **TPR 和 TNR 都重要** - 不只是一致性\n')
w('5. **盡可能用程式碼 eval** - LLM judge 在需要時使用\n')
w('6. **測試你的 eval** - 它們也可能有 bug\n')
w('7. **分割你的資料** - Train/Dev/Test 是不可缺少的\n')
w('8. **修正偏差** - 使用 judgy 獲得誠實的指標\n')
w('9. **對 prompt 進行版本控制** - 追蹤何時發生了什麼變化\n')
w('10. **基於資料迭代** - 而不是直覺\n')
w('\n')
w('---\n')
w('\n')
w('<a name="appendix-a"></a>\n')
w('<a id="appendix-a-glossary-for-pms--qas"></a>\n')
w('## 附錄 A：PM 與 QA 術語表\n')
w('\n')
w('本指南中使用的技術術語的通俗語言術語表。可與非技術利害關係人分享。\n')
w('\n')
w('<a id="evaluation--metrics-terms"></a>\n')
w('### 評測與指標術語\n')
w('\n')
w('| 術語 | 定義 |\n')
w('|------|--------|\n')
w('| **Eval（評測）** | 檢查 AI 系統是否對特定標準正確工作的系統性測試 |\n')
w('| **LLM-as-a-Judge** | 使用語言模型自動評估另一個 AI 系統的輸出 |\n')
w('| **基準真值（Ground Truth）** | 人工驗證的標籤，代表「正確」答案；用於量測 judge 準確性 |\n')
w('| **真正例率（TPR）** | judge 正確識別的實際正例（如好的回應）百分比。也稱為*召回率*或*敏感性*。公式：TP / (TP + FN) |\n')
w('| **真負例率（TNR）** | judge 正確捕獲的實際負例（如壞的回應）百分比。也稱為*特異性*。公式：TN / (TN + FP) |\n')
w('| **誤報（FP）** | judge 說「通過」但真實答案是「失敗」——漏掉的缺陷 |\n')
w('| **漏報（FN）** | judge 說「失敗」但真實答案是「通過」——虛假警報 |\n')
w('| **精確率（Precision）** | 在 judge 標注為正例的所有項目中，實際為正例的比例。公式：TP / (TP + FP) |\n')
w('| **F1 分數** | 精確率和召回率的調和平均數——平衡兩者的單一數字。公式：2 * (Precision * Recall) / (Precision + Recall) |\n')
w('| **混淆矩陣** | 顯示 TP、FP、FN、TN 計數的 2x2 表格——所有分類指標的基礎 |\n')
w('| **信賴區間（CI）** | 真實指標可能落在其中的值範圍（例如，72%-81%），考慮到抽樣不確定性 |\n')
w('| **偏差修正** | 調整原始 judge 分數以考慮系統性過度或低估通過/失敗 |\n')
w("| **Cohen's Kappa** | 量測兩個評分者（或評分者與基準真值）之間一致性的統計數，調整了偶然一致性。值：<0.2 差，0.4-0.6 中等，0.6-0.8 顯著，>0.8 幾乎完美 |\n")
w('\n')
w('<a id="data--workflow-terms"></a>\n')
w('### 資料與工作流程術語\n')
w('\n')
w('| 術語 | 定義 |\n')
w('|------|--------|\n')
w('| **Train/Dev/Test 分割** | 將標注資料分為三個集合：Train（用於建立 judge prompt）、Dev（用於迭代）、Test（用於最終無偏量測）|\n')
w('| **分層分割** | 分割資料使每個子集具有與原始資料相同比例的通過/失敗標籤 |\n')
w('| **少樣本範例（Few-Shot Examples）** | 包含在 prompt 中的輸入-輸出對範例，展示好的評測是什麼樣子 |\n')
w('| **開放編碼（Open Coding）** | 閱讀追蹤記錄並寫下有關問題的自由格式筆記——尚未分類 |\n')
w('| **軸向編碼（Axial Coding）** | 將你的開放編碼筆記分組為類別（錯誤類型）並計算頻率 |\n')
w('| **維度抽樣（Dimensional Sampling）** | 系統性地創建覆蓋所有重要維度的測試輸入（主題、邊緣案例、使用者類型）|\n')
w('| **失敗模式（Failure Mode）** | AI 系統失敗的具體命名方式（例如，「飲食違規」、「幻覺引用」）|\n')
w('| **錯誤分類法（Error Taxonomy）** | 你的應用程式所有失敗模式的有組織清單，按頻率和嚴重性排名 |\n')
w('\n')
w('<a id="observability--platform-terms"></a>\n')
w('### 可觀測性與平台術語\n')
w('\n')
w('| 術語 | 定義 |\n')
w('|------|--------|\n')
w('| **追蹤記錄（Trace）** | 一次 AI 互動的完整記錄——從使用者輸入到所有處理步驟到最終輸出 |\n')
w('| **跨度（Span）** | 追蹤記錄中的單一工作單元（例如，一個 LLM 呼叫、一次資料庫查詢、一次工具呼叫）|\n')
w('| **儀器化（Instrumentation）** | 在你的應用程式中添加程式碼，使追蹤記錄和跨度被自動捕獲 |\n')
w('| **資料集（Dataset）** | 儲存的範例集合（輸入 + 預期輸出），用於執行實驗 |\n')
w('| **實驗（Experiment）** | 在資料集上執行你的 AI 系統（或 judge）並記錄所有結果 |\n')
w('| **標注（Annotation）** | 附加到追蹤記錄或跨度的標籤或分數——可以是人工生成的或來自自動化 eval |\n')
w('| **Prompt 版本（Prompt Version）** | prompt 模板的已儲存快照，允許你追蹤更改並比較效能 |\n')
w('\n')
w('<a id="rag-specific-terms"></a>\n')
w('### RAG 專用術語\n')
w('\n')
w('| 術語 | 定義 |\n')
w('|------|--------|\n')
w('| **RAG（檢索增強生成）** | 在生成回應之前檢索相關文件的 AI 架構 |\n')
w('| **BM25** | 用作檢索品質基準的經典關鍵字搜尋演算法 |\n')
w('| **Recall@K** | 在所有相關文件中，有多少比例出現在前 K 個檢索結果中 |\n')
w('| **MRR（平均倒數排名）** | 第一個相關文件的 1/排名平均值——越高意味著相關文件出現得越早 |\n')
w('| **分塊（Chunking）** | 將大型文件分割為較小部分以供檢索 |\n')
w('| **上下文窗口（Context Window）** | LLM 在單次呼叫中可以處理的最大文本量 |\n')
w('| **幻覺（Hallucination）** | LLM 生成不受檢索上下文支持的資訊 |\n')
w('\n')
w('<a id="statistical-terms"></a>\n')
w('### 統計術語\n')
w('\n')
w('| 術語 | 定義 |\n')
w('|------|--------|\n')
w('| **p_obs（觀測率）** | 修正前 judge 的原始通過率 |\n')
w('| **θ̂（Theta-hat）** | 考慮 judge 錯誤後的修正後真實成功率 |\n')
w('| **judgy** | 計算修正後成功率和信賴區間的 Python 函式庫，給定 TPR 和 TNR |\n')
w('| **抽樣（Sampling）** | 評測追蹤記錄的隨機子集而不是全部——用於管理成本 |\n')
w('| **統計顯著性** | 觀察到的差異是否可能是真實的，或可能是由隨機機會造成的 |\n')
w('\n')
w('---\n')
w('\n')
w('<a name="appendix-b"></a>\n')
w('<a id="appendix-b-quick-reference"></a>\n')
w('## 附錄 B：快速參考\n')
w('\n')
w('<a id="when-to-use-what-type-of-eval"></a>\n')
w('### 何時使用哪種類型的 Eval\n')
w('\n')
w('| 情況 | 類型 | 範例 |\n')
w('|-----------|------|-------|\n')
w('| 格式檢查 | 程式碼型 | SMS 中沒有 Markdown |\n')
w('| 必填欄位 | 程式碼型 | 行程確認有日期/時間 |\n')
w('| 工具選擇 | 程式碼型 | 呼叫了正確的函式 |\n')
w('| 主觀品質 | LLM judge | 回應是有幫助的 |\n')
w('| 政策合規 | LLM judge | 符合移交要求 |\n')
w('| 飲食遵循 | LLM judge | 食譜遵循限制 |\n')
w('| 事實準確性 | LLM judge | 答案與來源匹配 |\n')
w('| 回應長度 | 程式碼型 | 500 字元以下 |\n')
w('\n')
w('<a id="metrics-cheat-sheet"></a>\n')
w('### 指標速查表\n')
w('\n')
w(cb(2712, 2727))
w('\n')
w('<a id="data-split-ratios"></a>\n')
w('### 資料分割比例\n')
w('\n')
w(cb(2731, 2735))
w('\n')
w('<a id="time-estimates"></a>\n')
w('### 時間估算\n')
w('\n')
w('| 活動 | 時間 | 頻率 |\n')
w('|----------|------|----------|\n')
w('| 初始設置（任何平台）| 2 小時 | 一次 |\n')
w('| 錯誤分析（100 條追蹤記錄）| 1 小時 | 每月 |\n')
w('| 建立程式碼型 eval | 1 小時 | 按需 |\n')
w('| 建立 LLM judge（完整流程）| 4-6 小時 | 按需 |\n')
w('| 在 Dev 集合上驗證 eval | 1 小時 | 每次迭代 |\n')
w('| 每週維護 | 30 分鐘 | 每週 |\n')
w('\n')
w('---\n')
w('\n')
w('<a name="appendix-c"></a>\n')
w('<a id="appendix-c-complete-judge-prompts-from-production"></a>\n')
w('## 附錄 C：生產環境的完整 Judge Prompt\n')
w('\n')
w('這是一個達到 TPR=95.7% 和 TNR=100% 的生產品質 judge prompt：\n')
w('\n')
w(cb(2755, 2809))
w('\n')
w('---\n')
w('\n')
w('<a name="appendix-d"></a>\n')
w('<a id="appendix-d-pipeline-state-evaluator-prompts"></a>\n')
w('## 附錄 D：流程狀態評測器 Prompt\n')
w('\n')
w('每個流程狀態的完整評測器 prompt。每個都遵循相同的結構：\n')
w('\n')
w('<a id="standard-evaluator-structure"></a>\n')
w('### 標準評測器結構\n')
w('\n')
w(cb(2820, 2828))
w('\n')
w('<a id="available-evaluators"></a>\n')
w('### 可用的評測器\n')
w('\n')
w('| 狀態 | 關鍵標準 | 常見失敗 |\n')
w('|-------|-------------|----------------|\n')
w('| ParseRequest | 準確性、完整性、格式 | 誤解、缺少限制 |\n')
w('| PlanToolCalls | 工具選擇、排序、理由 | 缺少工具、工具不正確 |\n')
w('| GenRecipeArgs | 查詢相關性、篩選準確性 | 缺少飲食篩選條件、份量錯誤 |\n')
w('| GetRecipes | 相關性、飲食合規性 | 不相關的食譜、飲食違規 |\n')
w('| GenWebArgs | 相關性、上下文對齊 | 偏題查詢、過於泛化 |\n')
w('| GetWebInfo | 相關性、品質 | 不相關的結果、偏題內容 |\n')
w('| ComposeResponse | 食譜準確性、步驟清晰度、限制合規性 | 矛盾、缺少資訊、違規 |\n')
w('\n')
w('---\n')
w('\n')
w('<a name="appendix-e"></a>\n')
w('<a id="appendix-e-judge-prompt-engineering-tips"></a>\n')
w('## 附錄 E：Judge Prompt 工程技巧\n')
w('\n')
w('一系列持續提高 LLM judge 準確性的技術。建立或除錯 judge 時使用此作為清單。\n')
w('\n')
w('<a id="1-explanation-before-verdict"></a>\n')
w('### 1. 判決前先解釋\n')
w('\n')
w('始終要求 judge 在給出最終標籤之前解釋其推理。這是影響最大的單一技術。\n')
w('\n')
w(cb(2866, 2872))
w('\n')
w('**為什麼有效：** 當模型先寫標籤時，解釋就成了事後合理化。當推理先來時，模型實際上在深思熟慮，標籤才能合乎邏輯地得出。\n')
w('\n')
w('<a id="2-be-ruthlessly-specific-about-criteria"></a>\n')
w('### 2. 對標準要無情地具體\n')
w('\n')
w('模糊的標準導致不一致的判斷。精確定義什麼算作通過和失敗。\n')
w('\n')
w(cb(2878, 2884))
w('\n')
w('<a id="3-include-what-does-not-count-as-a-failure"></a>\n')
w('### 3. 包含「什麼不算作失敗」\n')
w('\n')
w('Judge 往往過於嚴格。明確列出可接受的變化以校準寬鬆度。\n')
w('\n')
w(cb(2912, 2920))
w('\n')
w('<a id="4-use-domain-specific-few-shot-examples"></a>\n')
w('### 4. 使用特定領域的少樣本範例\n')
w('\n')
w('通用範例遠不如你實際資料中的範例有效。始終從你的 Train 集合中提取少樣本範例。\n')
w('\n')
w('**範例選擇策略：**\n')
w('- 1 個清晰的通過案例（簡單案例）\n')
w('- 1 個清晰的失敗案例（簡單案例）\n')
w('- 1 個邊緣案例（judge 最可能掙扎的類型）\n')
w('\n')
w('**在每個範例中包含推理**，而不只是標籤。Judge 學習的是推理模式，而不只是答案。\n')
w('\n')
w('<a id="5-temperature-settings"></a>\n')
w('### 5. Temperature 設置\n')
w('\n')
w('| 使用案例 | Temperature | 理由 |\n')
w('|----------|-------------|----------|\n')
w('| 二元分類（通過/失敗）| 0.0 | 確定性、可重現 |\n')
w('| Likert 評分（1-5）| 0.0-0.3 | 低變異性、一致 |\n')
w('| 生成多樣化批評 | 0.5-0.7 | 適度創造力 |\n')
w('| 腦力激盪失敗模式 | 0.7-1.0 | 高創造力用於探索 |\n')
w('\n')
w('<a id="6-structured-output-formats"></a>\n')
w('### 6. 結構化輸出格式\n')
w('\n')
w('精確告訴 judge 如何格式化其回應。JSON 是首選，因其解析可靠性。\n')
w('\n')
w(cb(2936, 2946))
w('\n')
w('<a id="7-guard-against-common-judge-biases"></a>\n')
w('### 7. 防範常見的 Judge 偏差\n')
w('\n')
w('| 偏差 | 描述 | 緩解方法 |\n')
w('|------|-------------|----------|\n')
w('| **寬鬆偏差** | Judge 預設「通過」太多 | 添加明確的失敗範例；強調「有疑問時，選失敗」|\n')
w('| **冗長偏差** | Judge 偏愛更長、更詳細的回應 | 添加短回應通過而長回應失敗的範例 |\n')
w('| **位置偏差** | Judge 偏愛清單中第一/最後的選項 | 如果比較多個輸出，隨機化順序 |\n')
w('| **諂媚偏差** | Judge 同意聽起來有信心的文本 | 添加有信心的文本是錯誤的範例 |\n')
w('| **錨定偏差** | Judge 受第一條證據影響 | 指示 judge 在得出結論之前考慮所有證據 |\n')
w('\n')
w('<a id="8-iterative-refinement-workflow"></a>\n')
w('### 8. 迭代精煉工作流程\n')
w('\n')
w(cb(2974, 2990))
w('\n')
w('<a id="9-model-selection-for-judges"></a>\n')
w('### 9. Judge 的模型選擇\n')
w('\n')
w('| 模型層級 | 使用時機 | 典型準確率 |\n')
w('|------------|------------|---------------|\n')
w('| GPT-4o / Claude Sonnet 4.6 | 高風險 eval、複雜推理 | 85-95% |\n')
w('| GPT-4o-mini / Claude Haiku | 成本敏感、大量 eval | 75-90% |\n')
w('| 開源（Llama、Mistral）| 自架、隱私敏感 | 70-85% |\n')
w('\n')
w('<a id="10-prompt-versioning"></a>\n')
w('### 10. Prompt 版本控制\n')
w('\n')
w('始終對你的 judge prompt 進行版本控制。追蹤：prompt 文字、使用的少樣本範例、模型和 temperature、Dev 集合指標（TPR、TNR）、日期和更改原因。\n')
w('\n')
w('Phoenix 和 Langfuse 都有內建的 prompt 版本控制。使用它。\n')
w('\n')
w('---\n')
w('\n')
w('<a name="appendix-f"></a>\n')
w('<a id="appendix-f-platform-methods-reference-phoenix--langfuse"></a>\n')
w('## 附錄 F：平台方法參考（Phoenix 與 Langfuse）\n')
w('\n')
w('<a id="phoenix-1"></a>\n')
w('### Phoenix\n')
w('\n')
w('<a id="tracing"></a>\n')
w('#### 追蹤記錄\n')
w('\n')
w(cb(3001, 3014))
w('\n')
w('<a id="querying-spans"></a>\n')
w('#### 查詢跨度\n')
w('\n')
w(cb(3018, 3030))
w('\n')
w('<a id="datasets"></a>\n')
w('#### 資料集\n')
w('\n')
w(cb(3034, 3042))
w('\n')
w('<a id="experiments"></a>\n')
w('#### 實驗\n')
w('\n')
w(cb(3046, 3059))
w('\n')
w('<a id="llm-evaluation-batch"></a>\n')
w('#### LLM 評測（批次）\n')
w('\n')
w(cb(3063, 3073))
w('\n')
w('<a id="prompt-management"></a>\n')
w('#### Prompt 管理\n')
w('\n')
w(cb(3077, 3088))
w('\n')
w('<a id="langfuse-2"></a>\n')
w('### Langfuse\n')
w('\n')
w('<a id="tracing-1"></a>\n')
w('#### 追蹤記錄\n')
w('\n')
w(cb(3094, 3109))
w('\n')
w('<a id="querying-traces"></a>\n')
w('#### 查詢追蹤記錄\n')
w('\n')
w(cb(3113, 3118))
w('\n')
w('<a id="datasets-1"></a>\n')
w('#### 資料集\n')
w('\n')
w(cb(3122, 3130))
w('\n')
w('<a id="experiments-1"></a>\n')
w('#### 實驗\n')
w('\n')
w(cb(3134, 3152))
w('\n')
w('<a id="scores-evaluation-results"></a>\n')
w('#### 分數（評測結果）\n')
w('\n')
w(cb(3156, 3169))
w('\n')
w('<a id="prompt-management-1"></a>\n')
w('#### Prompt 管理\n')
w('\n')
w(cb(3173, 3186))
w('\n')
w('---\n')
w('\n')
w('<a name="appendix-g"></a>\n')
w('<a id="appendix-g-30-day-learning-path"></a>\n')
w('## 附錄 G：30 天學習路徑\n')
w('\n')
w('<a id="week-1-foundations-engineer-pm-or-qa"></a>\n')
w('### 第 1 週：基礎（工程師、PM 或 QA）\n')
w('\n')
w('| 天 | 活動 | 時間 | 角色重點 |\n')
w('|-----|----------|------|------------|\n')
w('| 1 | 選擇你的平台（Phoenix 或 Langfuse），安裝它 | 1h | 所有人 |\n')
w('| 2 | 用自動追蹤為你的應用程式添加儀器 | 2h | 工程師 |\n')
w('| 2 | 瀏覽追蹤記錄查看器 UI，直觀理解追蹤記錄 | 1h | PM/QA |\n')
w('| 3 | 使用維度抽樣建立測試資料集 | 2h | 所有人 |\n')
w('| 4 | 將資料集上傳到你的平台，執行第一個實驗 | 1h | 所有人 |\n')
w('| 5 | 審閱 50 條追蹤記錄，做筆記（開放編碼）| 1h | 所有人 |\n')
w('| 6 | 使用 LLM 對錯誤進行分類（軸向編碼）| 1h | 所有人 |\n')
w('| 7 | 排定優先順序：頻率 x 嚴重性矩陣 | 30m | 所有人 |\n')
w('\n')
w('<a id="week-2-code-based-evals"></a>\n')
w('### 第 2 週：程式碼型 Eval\n')
w('\n')
w('| 天 | 活動 | 時間 | 角色重點 |\n')
w('|-----|----------|------|------------|\n')
w('| 8 | 為你的主要問題建立 2 個程式碼型 eval | 2h | 工程師 |\n')
w('| 8 | 用通俗語言定義 eval 標準 | 1h | PM/QA |\n')
w('| 9 | 用已知好/壞案例測試 eval | 1h | 所有人 |\n')
w('| 10 | 在所有追蹤記錄上執行 eval，計算失敗率 | 1h | 所有人 |\n')
w('| 11-14 | 根據結果進行迭代 | 2h | 所有人 |\n')
w('\n')
w('<a id="week-3-llm-judge"></a>\n')
w('### 第 3 週：LLM Judge\n')
w('\n')
w('| 天 | 活動 | 時間 | 角色重點 |\n')
w('|-----|----------|------|------------|\n')
w('| 15 | 標注 100-150 條追蹤記錄作為基準真值 | 3h | 所有人 |\n')
w('| 16 | 分割為 Train/Dev/Test | 30m | 工程師 |\n')
w('| 17 | 撰寫含少樣本範例的第一個 judge prompt | 2h | 所有人 |\n')
w('| 18 | 在 Dev 集合上驗證，計算 TPR/TNR | 1h | 所有人 |\n')
w('| 19 | 迭代 prompt 直到指標 > 80% | 2h | 所有人 |\n')
w('| 20 | 在 Test 集合上進行最終測試 | 30m | 所有人 |\n')
w('| 21 | 在所有追蹤記錄上執行 judge + 用 judgy 修正 | 1h | 所有人 |\n')
w('\n')
w('<a id="week-4-advanced-topics--production"></a>\n')
w('### 第 4 週：進階主題與生產\n')
w('\n')
w('| 天 | 活動 | 時間 | 角色重點 |\n')
w('|-----|----------|------|------------|\n')
w('| 22 | RAG 評測——檢索指標 + 答案品質（Ch. 6）| 2h | 工程師 |\n')
w('| 23 | 多步驟流程評測（Ch. 7）| 2h | 工程師 |\n')
w('| 24 | 多輪對話評測（Ch. 8）| 2h | 工程師 |\n')
w('| 25 | 安全 eval——prompt 注入、PII 洩漏（Ch. 9）| 2h | 所有人 |\n')
w('| 26 | 設置回歸測試套件（Ch. 11）| 2h | 工程師 |\n')
w('| 27 | 人工標注校準——量測標注者間一致性（Ch. 12）| 1h | 所有人 |\n')
w('| 28 | 為成本優化——分層評測、抽樣策略（Ch. 13）| 1h | 所有人 |\n')
w('| 29 | 建立監控儀表板 + 自動化 eval 執行 | 2h | 工程師 |\n')
w('| 30 | 記錄 eval 套件，向利害關係人報告，計劃維護 | 2h | 所有人 |\n')
w('\n')
w('---\n')
w('\n')
w('<a id="lessons-learned"></a>\n')
w('## 經驗教訓\n')
w('\n')
w('在生產環境中實施完整 eval 流程的真實教訓：\n')
w('\n')
w('**關於建立 Judge（Chapters 4, 10）**\n')
w('\n')
w('1. **LLM-as-Judge 強大但需要護欄** - 沒有適當驗證，judge 可以自信地給出錯誤答案。始終對基準真值進行驗證。\n')
w('\n')
w('2. **你必須對基準真值測試評測器** - TNR=22% 的 judge 看起來合理但實際上有害——它漏掉了大多數真實失敗。\n')
w('\n')
w('3. **Train/Dev/Test 分割帶來信心** - 沒有它們，你在欺騙自己關於 judge 品質的問題。這是不可缺少的。\n')
w('\n')
w('4. **迭代 judge prompt 至關重要** - 第一個 prompt 永遠不夠好。計劃至少 3-5 次迭代。詳見附錄 E。\n')
w('\n')
w('5. **解釋先於判決是第一技術** - 要求 judge 在標注前推理比任何其他單一更改更能提高準確性。\n')
w('\n')
w('**關於流程與方法論（Chapters 3, 11, 12）**\n')
w('\n')
w('6. **錯誤分析才是真正的工作** - 精美的工具不重要，如果你沒有坐下來審閱你的失敗。開放編碼→軸向編碼→優先排序是有效的工作流程。\n')
w('\n')
w("7. **人工標注者的分歧比你想像的更多** - 在信任你的基準真值之前量測標注者間一致性（Cohen's Kappa）。如果人類不能達成一致，judge 也不會。\n")
w('\n')
w('8. **閉環是優秀團隊與卓越團隊的分水嶺** - 執行 eval 只是工作的一半。另一半是系統性地將失敗轉化為改進並防止回歸。\n')
w('\n')
w('**關於生產與擴展（Chapters 9, 13）**\n')
w('\n')
w('9. **安全 eval 不是可選的** - Prompt 注入、PII 洩漏和越獄偵測應該在你擔心品質 eval 之前就運行。\n')
w('\n')
w('10. **先昂貴，再優化** - 使用 GPT-4o/Claude Sonnet 建立你的效能上限，然後測試更便宜的模型是否能匹配它。通常可以。\n')
w('\n')
w('11. **抽樣優於窮舉評測** - 用統計嚴謹性評測 10% 的追蹤記錄比用糟糕的 judge 評測 100% 給出更好的答案。\n')
w('\n')
w('12. **好的可觀測性工具使工作流程快 10 倍** - 在一個平台中整合追蹤記錄、評測、資料集和實驗（Phoenix、Langfuse 等）比拼湊自訂腳本節省大量時間。\n')
w('\n')
w('---\n')
w('\n')
w('<a id="conclusion"></a>\n')
w('## 結論\n')
w('\n')
w('AI eval 不只是「測試」——它是一種觸及工程、產品管理和品質保證的**產品開發方法論**。\n')
w('\n')
w('**關鍵要點：**\n')
w('\n')
w('1. **每個人都需要 eval** — 不只是大公司。如果你的 AI 應用接觸使用者，你需要系統性評測。\n')
w('2. **從錯誤分析開始** — 在建立任何自動化之前，坐下來審閱你的失敗（Chapter 3）。\n')
w('3. **PM 和 QA 必須主導** — 錯誤分析和標準定義是產品/品質工作，不只是工程任務。\n')
w('4. **逐步建立** — 從程式碼型 eval 開始，然後添加 LLM judge，然後添加安全 eval。不要試圖一次完成所有事情。\n')
w('5. **量測重要的事情** — 特定應用的標準，而不是通用的「有幫助性」分數。\n')
w('6. **TPR 和 TNR 都重要** — 捕獲失敗但也誤報的 judge 是有害的。兩者都要量測。\n')
w('7. **分割你的資料** — Train/Dev/Test 是必須的。沒有它，你就在過度擬合你的 judge。\n')
w('8. **修正偏差** — 使用統計修正（Chapter 10）獲得誠實的指標。\n')
w('9. **閉環** — 不能帶來改進的 eval 是浪費的努力（Chapter 11）。\n')
w('10. **為規模計劃** — 從最好的模型開始，然後為成本優化（Chapter 13）。\n')
w('\n')
w('**你的行動計劃（詳見附錄 G）：**\n')
w('\n')
w('1. 第 1 週：設置可觀測性（Phoenix、Langfuse 或你選擇的工具），進行錯誤分析\n')
w('2. 第 2 週：建立 2-3 個核心程式碼型 eval\n')
w('3. 第 3 週：建立並驗證帶有適當 train/dev/test 分割的 LLM judge\n')
w('4. 第 4 週：進階主題——RAG eval、多輪 eval、安全 eval、自動化\n')
w('5. 持續進行：每週 30 分鐘維護 + 回歸測試\n')
w('\n')
w('**記住：** 發布最佳 AI 產品的團隊，是那些擁有最佳 eval 的團隊。不是最先進的模型。不是最大的團隊。是那些系統性量測和改進的團隊。\n')
w('\n')
w('今天就開始。你未來的自己會感謝你。\n')
w('\n')
w('---\n')
w('\n')
w('<a id="learning-resources"></a>\n')
w('## 學習資源\n')
w('\n')
w('<a id="platform-documentation--learning-hubs"></a>\n')
w('### 平台文件與學習中心\n')
w('\n')
w('- **Phoenix 文件**：[docs.arize.com/phoenix](https://docs.arize.com/phoenix)\n')
w('- **Arize 部落格與學習中心**：[arize.com/blog](https://arize.com/blog/)\n')
w('- **Langfuse 文件**：[langfuse.com/docs](https://langfuse.com/docs)\n')
w('- **Maven 課程（工程師與 PM 的 AI Evals）**：[maven.com/parlance-labs/evals](https://maven.com/parlance-labs/evals)\n')
w('- **HuggingFace 評測指南**：[github.com/huggingface/evaluation-guidebook](https://github.com/huggingface/evaluation-guidebook)\n')
w('\n')
w('<a id="research--thought-leadership"></a>\n')
w('### 研究與思想領導力\n')
w('\n')
w('- **OpenAI Evals 平台**：[evals.openai.com](https://evals.openai.com/)\n')
w('- **OpenAI Cookbook**（實用範例與指南）：[cookbook.openai.com](https://cookbook.openai.com/)\n')
w('- **OpenAI 研究**：[openai.com/research](https://openai.com/research)\n')
w('- **OpenAI 文件（Evals）**：[platform.openai.com/docs/guides/evals](https://platform.openai.com/docs/guides/evals)\n')
w('- **Anthropic 研究**：[anthropic.com/research](https://www.anthropic.com/research)\n')
w('- **METR**（模型評測與威脅研究）：[metr.org](https://metr.org/)\n')
w('- **Eugene Yan 關於 eval 流程**：[eugeneyan.com/writing/eval-process](https://eugeneyan.com/writing/eval-process/)\n')
w('\n')
w('<a id="blogs-that-shaped-this-guide"></a>\n')
w('### 塑造本指南的部落格\n')
w('\n')
w('- **Hamel Husain 的部落格**：[hamel.dev](https://hamel.dev/) — 應用 AI 工程、LLM eval 深度探討\n')
w('- **Shreya Shankar 的網站**：[sh-reya.com](https://www.sh-reya.com/) — LLM 資料系統研究、eval 方法論\n')
w('- **Maxim AI 文章**：[getmaxim.ai/articles](https://www.getmaxim.ai/articles) — 代理評測模式\n')
w('\n')
w('<a id="open-source-tools--libraries"></a>\n')
w('### 開源工具與函式庫\n')
w('\n')
w('| 工具 | 重點 | 授權 | 連結 |\n')
w('|------|-------|---------|-------|\n')
w('| **Arize Phoenix** | 可觀測性與 eval | ELv2 | [GitHub](https://github.com/Arize-ai/phoenix) · [文件](https://docs.arize.com/phoenix) |\n')
w('| **Langfuse** | 自訂流程與追蹤 | MIT | [GitHub](https://github.com/langfuse/langfuse) · [文件](https://langfuse.com/docs) |\n')
w('| **RAGAS** | RAG 專用評測 | Apache 2.0 | [GitHub](https://github.com/explodinggradients/ragas) · [文件](https://docs.ragas.io/) |\n')
w('| **Comet Opik** | LLM 追蹤與評測 | Apache 2.0 | [GitHub](https://github.com/comet-ml/opik) · [網站](https://www.comet.com/site/products/opik/) |\n')
w('| **judgy** | 統計偏差修正 | 開源 | [GitHub](https://github.com/ai-evals-course/judgy) |\n')
w('| **Braintrust** | 實驗與日誌記錄 | 部分開源 | [文件](https://www.braintrust.dev/docs) |\n')
w('| **Galileo** | 幻覺偵測 | 專有 | [網站](https://www.galileo.ai/) |\n')
w('| **Maxim** | 代理系統評測 | 專有 | [網站](https://www.getmaxim.ai/) |\n')
w('\n')
w('<a id="strategy-comparison-matrix"></a>\n')
w('### 策略比較矩陣\n')
w('\n')
w('| 公司 | 重點 | 開源 | 最適合 | 獨特優勢 |\n')
w('|---------|-------|-------------|----------|------------------|\n')
w('| **Anthropic** | 安全/紅隊 | 部分 | 前沿風險 | 憲法分類器、多次嘗試對抗測試 |\n')
w('| **OpenAI** | 準備度/商業 | Evals 工具包 | 企業上下文 | SME 探測、上下文 eval |\n')
w('| **Arize** | 可觀測性 | Phoenix (ELv2) | 生產規模 | OTel 原生、資料湖整合 |\n')
w('| **RAGAS** | RAG 專用 | 是 (Apache 2.0) | RAG 流程 | 無參考指標、合成測試資料生成 |\n')
w('| **Maxim** | 代理系統 | 否 | 多代理應用 | 模擬框架、無程式碼評測 |\n')
w('| **Langfuse** | 自訂流程 | 是 (MIT) | 資料主權 | 可自架、完全資料控制 |\n')
w('| **Braintrust** | 實驗 | 部分 | 早期階段團隊 | 協作設計、快速迭代 |\n')
w('| **Galileo** | 幻覺 | 否 | 品質保證 | ChainPoll、即時監控 |\n')
w('| **Comet Opik** | LLM 追蹤與 Eval | 是 (Apache 2.0) | 端到端可觀測性 | 框架整合、線上評測規則 |\n')
w('| **METR** | 災難性風險 | 研究 | 政策指導 | 自主能力評估 |\n')
w('\n')
w('<a id="contact-me"></a>\n')
w('### 聯絡我\n')
w('- Om Bharatiya：[@ombharatiya](https://twitter.com/ombharatiya)\n')
w('\n')
w('<a id="reference-work-credits"></a>\n')
w('### 參考作品致謝\n')
w('本指南建立在以下人員的工作和想法之上。他們的課程、部落格和開源貢獻使本指南成為可能：\n')
w('- Hamel Husain：[@HamelHusain](https://x.com/HamelHusain) — [hamel.dev](https://hamel.dev/)\n')
w('- Shreya Shankar：[@sh_reya](https://x.com/sh_reya) — [sh-reya.com](https://www.sh-reya.com/)\n')
w('- Eugene Yan：[@eugeneyan](https://x.com/eugeneyan) — [eugeneyan.com](https://eugeneyan.com/)\n')
w('\n')
w('---\n')
w('\n')
w('*本指南受到 Hamel Husain 和 Shreya Shankar 的「工程師與 PM 的 AI Evals」課程啟發，並在此基礎上擴展，包含額外研究、生產就緒程式碼範例，以及涵蓋 Phoenix、Langfuse 和更廣泛 eval 工具生態系統的多平台指南。*\n')
w('\n')
w('*作者：Om Bharatiya | 創建：2026 年 2 月*\n')
